using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using System.Diagnostics;
using Microsoft.Win32;
using Microsoft.WindowsAPICodePack.Dialogs;

namespace Etrian_Odyssey_IV_test
{
    public partial class FormQSkillEditor : Form
    {
        String treeloaded = "No";
        byte[] enemydata_array; //This starts the array, the name after is what i name this array?
        public FormQSkillEditor()
        {
            InitializeComponent();

            string enemydata_path = Properties.Settings.Default.PQRomFS + "\\battle\\table\\skilltable.tbl"; //This defines the path as a string, so i can refer to it by this string/name instead of the full path every time
            int enemydata_length = (int)(new FileInfo(enemydata_path).Length);   //The leagth of the array?
            enemydata_array = File.ReadAllBytes(enemydata_path);  //loads an array with whatever is in the path

            //Add the EO1 enemy list to the in editor list of enemy names
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Attack");
            enemyTree.Nodes.Add("Agi");
            enemyTree.Nodes.Add("Agilao");
            enemyTree.Nodes.Add("Agidyne");
            enemyTree.Nodes.Add("Maragi");
            enemyTree.Nodes.Add("Maragion");
            enemyTree.Nodes.Add("Maragidyne");
            enemyTree.Nodes.Add("Fire Spray");
            enemyTree.Nodes.Add("Ragnarok");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Garu");
            enemyTree.Nodes.Add("Garula");
            enemyTree.Nodes.Add("Garudyne");
            enemyTree.Nodes.Add("Magaru");
            enemyTree.Nodes.Add("Magarula");
            enemyTree.Nodes.Add("Magarudyne");
            enemyTree.Nodes.Add("Cyclone");
            enemyTree.Nodes.Add("Panta Rhei");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Bufu");
            enemyTree.Nodes.Add("Bufula");
            enemyTree.Nodes.Add("Bufudyne");
            enemyTree.Nodes.Add("Mabufu");
            enemyTree.Nodes.Add("Mabufula");
            enemyTree.Nodes.Add("Mabufudyne");
            enemyTree.Nodes.Add("Icy Paradise");
            enemyTree.Nodes.Add("Niflheim");
            enemyTree.Nodes.Add("Frozen Spear");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Zio");
            enemyTree.Nodes.Add("Zionga");
            enemyTree.Nodes.Add("Ziodyne");
            enemyTree.Nodes.Add("Mazio");
            enemyTree.Nodes.Add("Mazionga");
            enemyTree.Nodes.Add("Maziodyne");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Thunder Reign");
            enemyTree.Nodes.Add("Keraunos");
            enemyTree.Nodes.Add("Thunder Clap");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Megido");
            enemyTree.Nodes.Add("Megidola");
            enemyTree.Nodes.Add("Megidolaon");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Black Viper");
            enemyTree.Nodes.Add("Morning Star");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Hama");
            enemyTree.Nodes.Add("Hamaon");
            enemyTree.Nodes.Add("Mahama");
            enemyTree.Nodes.Add("Mahamaon");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Samsara");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Mudo");
            enemyTree.Nodes.Add("Mudoon");
            enemyTree.Nodes.Add("Mamudo");
            enemyTree.Nodes.Add("Mamudoon");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Die For Me!");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Pulinpa");
            enemyTree.Nodes.Add("Tentarafoo");
            enemyTree.Nodes.Add("Poisma");
            enemyTree.Nodes.Add("Poison Breath");
            enemyTree.Nodes.Add("Gambit");
            enemyTree.Nodes.Add("Flashbang");
            enemyTree.Nodes.Add("Dormina");
            enemyTree.Nodes.Add("Lullaby Song");
            enemyTree.Nodes.Add("Evil Touch");
            enemyTree.Nodes.Add("Evil Smile");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Heavy Gi");
            enemyTree.Nodes.Add("Bracer of Might");
            enemyTree.Nodes.Add("Sacrificial Idol");
            enemyTree.Nodes.Add("Rudra Ring");
            enemyTree.Nodes.Add("Chakra Ring");
            enemyTree.Nodes.Add("Willow Wing");
            enemyTree.Nodes.Add("Snowy Wing");
            enemyTree.Nodes.Add("Enduring Wing");
            enemyTree.Nodes.Add("Blazing Flame");
            enemyTree.Nodes.Add("Frozen Stone");
            enemyTree.Nodes.Add("Storm Ring");
            enemyTree.Nodes.Add("Lightning Gloves");
            enemyTree.Nodes.Add("Radiant Halo");
            enemyTree.Nodes.Add("Ring of Darkness");
            enemyTree.Nodes.Add("Bladed Plume");
            enemyTree.Nodes.Add("Iron Pendant");
            enemyTree.Nodes.Add("Helmet");
            enemyTree.Nodes.Add("Omnipotent Orb");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Germanium Ring");
            enemyTree.Nodes.Add("Scapegoat");
            enemyTree.Nodes.Add("Body-Soul Reverse");
            enemyTree.Nodes.Add("St-Ma Reverse");
            enemyTree.Nodes.Add("St-En Reverse");
            enemyTree.Nodes.Add("St-Ag Reverse");
            enemyTree.Nodes.Add("St-Lu Reverse");
            enemyTree.Nodes.Add("Ma-En Reverse");
            enemyTree.Nodes.Add("Ma-Ag Reverse");
            enemyTree.Nodes.Add("Ma-Lu Reverse");
            enemyTree.Nodes.Add("En-Ag Reverse");
            enemyTree.Nodes.Add("En-Lu Reverse");
            enemyTree.Nodes.Add("Ag-Lu Reverse");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Physical Start");
            enemyTree.Nodes.Add("Fang Smash");
            enemyTree.Nodes.Add("Kidney Smash");
            enemyTree.Nodes.Add("Cleave");
            enemyTree.Nodes.Add("Twin Slash");
            enemyTree.Nodes.Add("End Shot");
            enemyTree.Nodes.Add("Double Shot");
            enemyTree.Nodes.Add("Mighty Swing");
            enemyTree.Nodes.Add("Fatal End");
            enemyTree.Nodes.Add("Silent Thrust");
            enemyTree.Nodes.Add("Swift Strike");
            enemyTree.Nodes.Add("Frost Edge");
            enemyTree.Nodes.Add("Zanshinken");
            enemyTree.Nodes.Add("Zanshin Strike");
            enemyTree.Nodes.Add("Death Needle");
            enemyTree.Nodes.Add("Guillotine");
            enemyTree.Nodes.Add("Tempest Slash");
            enemyTree.Nodes.Add("Bolt Strike");
            enemyTree.Nodes.Add("Holy Touch");
            enemyTree.Nodes.Add("Revenge Blow");
            enemyTree.Nodes.Add("Revenge Strike");
            enemyTree.Nodes.Add("Gigantic Fist");
            enemyTree.Nodes.Add("Single Shot");
            enemyTree.Nodes.Add("Scarecrow");
            enemyTree.Nodes.Add("Disarm");
            enemyTree.Nodes.Add("Makajam");
            enemyTree.Nodes.Add("Assault Shot");
            enemyTree.Nodes.Add("Primal Force");
            enemyTree.Nodes.Add("Heavy Shot");
            enemyTree.Nodes.Add("Broadshot");
            enemyTree.Nodes.Add("Myriad Arrows");
            enemyTree.Nodes.Add("Punishment");
            enemyTree.Nodes.Add("Assault Dive");
            enemyTree.Nodes.Add("Sleeper Punch");
            enemyTree.Nodes.Add("Teardrop");
            enemyTree.Nodes.Add("Buchikamashi");
            enemyTree.Nodes.Add("Deathbound");
            enemyTree.Nodes.Add("Blade of Fury");
            enemyTree.Nodes.Add("Glacial Edge");
            enemyTree.Nodes.Add("Vorpal Blade");
            enemyTree.Nodes.Add("Danse Macabre");
            enemyTree.Nodes.Add("Skull Cracker");
            enemyTree.Nodes.Add("Fusion Blast");
            enemyTree.Nodes.Add("Heat Wave");
            enemyTree.Nodes.Add("Light Wave");
            enemyTree.Nodes.Add("Paralysis");
            enemyTree.Nodes.Add("Brutal Slash");
            enemyTree.Nodes.Add("Photon Edge");
            enemyTree.Nodes.Add("Prana");
            enemyTree.Nodes.Add("Heaven's Blade");
            enemyTree.Nodes.Add("God's Hand");
            enemyTree.Nodes.Add("Angelic Trumpet");
            enemyTree.Nodes.Add("Hassou Tobi");
            enemyTree.Nodes.Add("Hailstorm");
            enemyTree.Nodes.Add("Arrow Rain");
            enemyTree.Nodes.Add("Aeon Rain");
            enemyTree.Nodes.Add("Blinding Slice");
            enemyTree.Nodes.Add("Toxic Slice");
            enemyTree.Nodes.Add("Dream Slice");
            enemyTree.Nodes.Add("Stunning Slice");
            enemyTree.Nodes.Add("Bane Slice");
            enemyTree.Nodes.Add("Gurentou");
            enemyTree.Nodes.Add("Tousatsujin");
            enemyTree.Nodes.Add("Raikouzan");
            enemyTree.Nodes.Add("Jinpugeki");
            enemyTree.Nodes.Add("Shinkuuha");
            enemyTree.Nodes.Add("Resseiha");
            enemyTree.Nodes.Add("Pralaya");
            enemyTree.Nodes.Add("Shadow Run");
            enemyTree.Nodes.Add("World's End");
            enemyTree.Nodes.Add("Raimeizan");
            enemyTree.Nodes.Add("Raijinzan");
            enemyTree.Nodes.Add("Gokuentou");
            enemyTree.Nodes.Add("Hientou");
            enemyTree.Nodes.Add("Reppu Strike");
            enemyTree.Nodes.Add("Kamikaze Strike");
            enemyTree.Nodes.Add("Hex Slice");
            enemyTree.Nodes.Add("Soul Slice");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Physical End");
            enemyTree.Nodes.Add("Support Start");
            enemyTree.Nodes.Add("Dia");
            enemyTree.Nodes.Add("Diarama");
            enemyTree.Nodes.Add("Diarahan");
            enemyTree.Nodes.Add("Recovery");
            enemyTree.Nodes.Add("Life Goblet");
            enemyTree.Nodes.Add("Media");
            enemyTree.Nodes.Add("Mediarama");
            enemyTree.Nodes.Add("Mediarahan");
            enemyTree.Nodes.Add("Recarm");
            enemyTree.Nodes.Add("Samarecarm");
            enemyTree.Nodes.Add("Treatment");
            enemyTree.Nodes.Add("Renewal");
            enemyTree.Nodes.Add("Patra");
            enemyTree.Nodes.Add("Refresh");
            enemyTree.Nodes.Add("Me Patra");
            enemyTree.Nodes.Add("Mutudi");
            enemyTree.Nodes.Add("Becalm");
            enemyTree.Nodes.Add("Mamutudi");
            enemyTree.Nodes.Add("Amrita");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Bestial Roar");
            enemyTree.Nodes.Add("Dragon Cry");
            enemyTree.Nodes.Add("Improved Link");
            enemyTree.Nodes.Add("Master Link");
            enemyTree.Nodes.Add("Shadow Cloak");
            enemyTree.Nodes.Add("Rampart");
            enemyTree.Nodes.Add("Pain-Eater");
            enemyTree.Nodes.Add("Safeguard");
            enemyTree.Nodes.Add("Body Shield");
            enemyTree.Nodes.Add("Life Wall");
            enemyTree.Nodes.Add("True Warden");
            enemyTree.Nodes.Add("Holy Blessing");
            enemyTree.Nodes.Add("Guiding Sword");
            enemyTree.Nodes.Add("Guarding Staff");
            enemyTree.Nodes.Add("Spotter");
            enemyTree.Nodes.Add("Critical Eye");
            enemyTree.Nodes.Add("Makara Boost");
            enemyTree.Nodes.Add("Matarukaja");
            enemyTree.Nodes.Add("Marakukaja");
            enemyTree.Nodes.Add("Masukukaja");
            enemyTree.Nodes.Add("Power Charge");
            enemyTree.Nodes.Add("Mind Charge");
            enemyTree.Nodes.Add("Fire Blessing");
            enemyTree.Nodes.Add("Ice Blessing");
            enemyTree.Nodes.Add("Elec Blessing");
            enemyTree.Nodes.Add("Wind Blessing");
            enemyTree.Nodes.Add("Quick Order");
            enemyTree.Nodes.Add("Daunting Stare");
            enemyTree.Nodes.Add("Piercing Stare");
            enemyTree.Nodes.Add("Tetra Down");
            enemyTree.Nodes.Add("Makara Down");
            enemyTree.Nodes.Add("Matarunda");
            enemyTree.Nodes.Add("Marakunda");
            enemyTree.Nodes.Add("Masukunda");
            enemyTree.Nodes.Add("Rear Guard");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Stagnant Air");
            enemyTree.Nodes.Add("Salome's Kiss");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Dekaja");
            enemyTree.Nodes.Add("Dekunda");
            enemyTree.Nodes.Add("Heat Sink");
            enemyTree.Nodes.Add("Makatora");
            enemyTree.Nodes.Add("Decoy Sign");
            enemyTree.Nodes.Add("Fire Wall");
            enemyTree.Nodes.Add("Wind Wall");
            enemyTree.Nodes.Add("Ice Wall");
            enemyTree.Nodes.Add("Elec Wall");
            enemyTree.Nodes.Add("Light Wall");
            enemyTree.Nodes.Add("Dark Wall");
            enemyTree.Nodes.Add("Tarukaja");
            enemyTree.Nodes.Add("Rakukaja");
            enemyTree.Nodes.Add("Sukukaja");
            enemyTree.Nodes.Add("Tarunda");
            enemyTree.Nodes.Add("Rakunda");
            enemyTree.Nodes.Add("Sukunda");
            enemyTree.Nodes.Add("Debilitate");
            enemyTree.Nodes.Add("Heat Riser");
            enemyTree.Nodes.Add("Mind's Eye");
            enemyTree.Nodes.Add("Door of Hades");
            enemyTree.Nodes.Add("Call to Hades");
            enemyTree.Nodes.Add("Calamity Seed");
            enemyTree.Nodes.Add("Calamity Advent");
            enemyTree.Nodes.Add("Lunar Blessing");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Healing Harp");
            enemyTree.Nodes.Add("Healing Harp");
            enemyTree.Nodes.Add("Lightning Smash");
            enemyTree.Nodes.Add("Thunder Smash");
            enemyTree.Nodes.Add("Scorching Blast");
            enemyTree.Nodes.Add("Nuclear Blast");
            enemyTree.Nodes.Add("Sonic Punch");
            enemyTree.Nodes.Add("Brain Shake");
            enemyTree.Nodes.Add("Moondrop");
            enemyTree.Nodes.Add("Stardrop");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Support End");
            enemyTree.Nodes.Add("Leader Start");
            enemyTree.Nodes.Add("All-Out Attack");
            enemyTree.Nodes.Add("Sutakora Foot");
            enemyTree.Nodes.Add("Analyze");
            enemyTree.Nodes.Add("Full Analysis");
            enemyTree.Nodes.Add("Snake Glare");
            enemyTree.Nodes.Add("Heroic Wind");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Harvest Prayer");
            enemyTree.Nodes.Add("Cornucopia");
            enemyTree.Nodes.Add("Healing Tide");
            enemyTree.Nodes.Add("Healing Tide");
            enemyTree.Nodes.Add("Renewal Ray");
            enemyTree.Nodes.Add("Renewal Aura");
            enemyTree.Nodes.Add("Healing Breeze");
            enemyTree.Nodes.Add("Spotlight");
            enemyTree.Nodes.Add("Yomi Return");
            enemyTree.Nodes.Add("Third Eye");
            enemyTree.Nodes.Add("Orb of Resolve");
            enemyTree.Nodes.Add("Orb of Power");
            enemyTree.Nodes.Add("Orb of Haste");
            enemyTree.Nodes.Add("Life Aid");
            enemyTree.Nodes.Add("Victory Cry");
            enemyTree.Nodes.Add("Safety Prayer");
            enemyTree.Nodes.Add("Calming Lull");
            enemyTree.Nodes.Add("Spotter");
            enemyTree.Nodes.Add("Magic Mallet");
            enemyTree.Nodes.Add("Fanfare");
            enemyTree.Nodes.Add("Into the Void");
            enemyTree.Nodes.Add("Tidal Wave");
            enemyTree.Nodes.Add("Oracle");
            enemyTree.Nodes.Add("Oracle");
            enemyTree.Nodes.Add("Oracle");
            enemyTree.Nodes.Add("Oracle");
            enemyTree.Nodes.Add("Oracle");
            enemyTree.Nodes.Add("Oracle");
            enemyTree.Nodes.Add("Healing Breeze");
            enemyTree.Nodes.Add("Absolute Camera");
            enemyTree.Nodes.Add("Prayer");
            enemyTree.Nodes.Add("Vigilant Sonar");
            enemyTree.Nodes.Add("Treasure Hunter");
            enemyTree.Nodes.Add("Fortune Hunter");
            enemyTree.Nodes.Add("Faerie's Vigil");
            enemyTree.Nodes.Add("Tengu's Vigil");
            enemyTree.Nodes.Add("Clairvoyance");
            enemyTree.Nodes.Add("Farsight");
            enemyTree.Nodes.Add("Purifying Rain");
            enemyTree.Nodes.Add("Material Cache");
            enemyTree.Nodes.Add("Zero Set");
            enemyTree.Nodes.Add("Eternal Melody");
            enemyTree.Nodes.Add("Lavish Gift");
            enemyTree.Nodes.Add("Holy Gift");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Hunting Prayer");
            enemyTree.Nodes.Add("Endless Bounty");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Alleys of Light");
            enemyTree.Nodes.Add("Paths of Light");
            enemyTree.Nodes.Add("Roads of Light");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Start");
            enemyTree.Nodes.Add("Stun Circle");
            enemyTree.Nodes.Add("Magic Circle");
            enemyTree.Nodes.Add("Sleep Circle");
            enemyTree.Nodes.Add("Magic Circle");
            enemyTree.Nodes.Add("Poison Circle");
            enemyTree.Nodes.Add("Magic Circle");
            enemyTree.Nodes.Add("Panic Circle");
            enemyTree.Nodes.Add("Magic Circle");
            enemyTree.Nodes.Add("Silence Circle");
            enemyTree.Nodes.Add("Magic Circle");
            enemyTree.Nodes.Add("Decay Circle");
            enemyTree.Nodes.Add("Magic Circle");
            enemyTree.Nodes.Add("Lethargy Circle");
            enemyTree.Nodes.Add("Magic Circle");
            enemyTree.Nodes.Add("Summon Ghost");
            enemyTree.Nodes.Add("Summon Demon");
            enemyTree.Nodes.Add("Shura Tensei");
            enemyTree.Nodes.Add("Shura Revert");
            enemyTree.Nodes.Add("Shura Instincts");
            enemyTree.Nodes.Add("Orgia Mode");
            enemyTree.Nodes.Add("Mode Disengage");
            enemyTree.Nodes.Add("Heal Memento");
            enemyTree.Nodes.Add("Heal Memento");
            enemyTree.Nodes.Add("Free Memento");
            enemyTree.Nodes.Add("Free Memento");
            enemyTree.Nodes.Add("Pure Memento");
            enemyTree.Nodes.Add("Pure Memento");
            enemyTree.Nodes.Add("Blessing of Relief");
            enemyTree.Nodes.Add("Death Counter");
            enemyTree.Nodes.Add("Death Counter");
            enemyTree.Nodes.Add("Death Chaser");
            enemyTree.Nodes.Add("Death Chaser");
            enemyTree.Nodes.Add("Fierce Stance");
            enemyTree.Nodes.Add("Fierce Stance");
            enemyTree.Nodes.Add("Ferocious Stance");
            enemyTree.Nodes.Add("Guard Stance");
            enemyTree.Nodes.Add("Healing Step");
            enemyTree.Nodes.Add("Wide Dance");
            enemyTree.Nodes.Add("Rush Dance");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Flame Link");
            enemyTree.Nodes.Add("Flame Link");
            enemyTree.Nodes.Add("Frost Link");
            enemyTree.Nodes.Add("Frost Link");
            enemyTree.Nodes.Add("Bolt Link");
            enemyTree.Nodes.Add("Bolt Link");
            enemyTree.Nodes.Add("Gale Link");
            enemyTree.Nodes.Add("Gale Link");
            enemyTree.Nodes.Add("Pain Watcher");
            enemyTree.Nodes.Add("Auto-Cloak");
            enemyTree.Nodes.Add("Rush Dance");
            enemyTree.Nodes.Add("Splash Blessing");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("End");
            enemyTree.Nodes.Add("Start");
            enemyTree.Nodes.Add("Orgia Mastery");
            enemyTree.Nodes.Add("Spy Arts");
            enemyTree.Nodes.Add("Spy Expertise");
            enemyTree.Nodes.Add("Pose");
            enemyTree.Nodes.Add("Heroic Pose");
            enemyTree.Nodes.Add("Hermit Arts");
            enemyTree.Nodes.Add("Hermit Mastery");
            enemyTree.Nodes.Add("Bloody Vanguard");
            enemyTree.Nodes.Add("Deadly Vanguard");
            enemyTree.Nodes.Add("Empress Arts");
            enemyTree.Nodes.Add("Empress Mastery");
            enemyTree.Nodes.Add("Squire Card");
            enemyTree.Nodes.Add("Knight Card");
            enemyTree.Nodes.Add("Soldier Arts");
            enemyTree.Nodes.Add("Soldier Mastery");
            enemyTree.Nodes.Add("Kung Fu Arts");
            enemyTree.Nodes.Add("Kung Fu Mastery");
            enemyTree.Nodes.Add("Wild Arts");
            enemyTree.Nodes.Add("Wild Arts +");
            enemyTree.Nodes.Add("Brave Soul");
            enemyTree.Nodes.Add("Brave Soul +");
            enemyTree.Nodes.Add("Rebel Spirit");
            enemyTree.Nodes.Add("Uprising");
            enemyTree.Nodes.Add("Circle Master");
            enemyTree.Nodes.Add("Circle Virtuoso");
            enemyTree.Nodes.Add("Brawler Arts");
            enemyTree.Nodes.Add("Brawler Arts +");
            enemyTree.Nodes.Add("Life Support");
            enemyTree.Nodes.Add("Life Support +");
            enemyTree.Nodes.Add("Stance Master");
            enemyTree.Nodes.Add("Stance Virtuoso");
            enemyTree.Nodes.Add("Raging Lion");
            enemyTree.Nodes.Add("Raging Lion +");
            enemyTree.Nodes.Add("Heroic Gemini");
            enemyTree.Nodes.Add("Golden Gemini");
            enemyTree.Nodes.Add("Runic Shield");
            enemyTree.Nodes.Add("Aegis Shield");
            enemyTree.Nodes.Add("Swordbreaker");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("First Star");
            enemyTree.Nodes.Add("Binding Hands");
            enemyTree.Nodes.Add("Restoring Touch");
            enemyTree.Nodes.Add("Warrior Title");
            enemyTree.Nodes.Add("Conqueror Title");
            enemyTree.Nodes.Add("Conqueror Arts");
            enemyTree.Nodes.Add("Healing Hand");
            enemyTree.Nodes.Add("Dia Guard");
            enemyTree.Nodes.Add("Diarama Guard");
            enemyTree.Nodes.Add("Colossal Swing");
            enemyTree.Nodes.Add("Whirlwind Swing");
            enemyTree.Nodes.Add("Golden Link");
            enemyTree.Nodes.Add("Perception");
            enemyTree.Nodes.Add("Forked Spear");
            enemyTree.Nodes.Add("Trick Step");
            enemyTree.Nodes.Add("Endure");
            enemyTree.Nodes.Add("Nature's Grace");
            enemyTree.Nodes.Add("Immunity Buffer");
            enemyTree.Nodes.Add("Lemegeton");
            enemyTree.Nodes.Add("Platinum Coin");
            enemyTree.Nodes.Add("Absorb Fire");
            enemyTree.Nodes.Add("Absorb Wind");
            enemyTree.Nodes.Add("Absorb Ice");
            enemyTree.Nodes.Add("Absorb Elec");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Fire Boost");
            enemyTree.Nodes.Add("Ice Boost");
            enemyTree.Nodes.Add("Elec Boost");
            enemyTree.Nodes.Add("Wind Boost");
            enemyTree.Nodes.Add("Fire Amp");
            enemyTree.Nodes.Add("Ice Amp");
            enemyTree.Nodes.Add("Elec Amp");
            enemyTree.Nodes.Add("Wind Amp");
            enemyTree.Nodes.Add("Overheat SP Boost");
            enemyTree.Nodes.Add("Devotion Arts");
            enemyTree.Nodes.Add("Devotion Mastery");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Death's Scythe");
            enemyTree.Nodes.Add("Impure Reach");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Circle Recovery");
            enemyTree.Nodes.Add("King Card");
            enemyTree.Nodes.Add("Inferno Boost");
            enemyTree.Nodes.Add("Tornado Boost");
            enemyTree.Nodes.Add("Powerhouse");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("SP Focus");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Target Boost");
            enemyTree.Nodes.Add("Attack Boost I");
            enemyTree.Nodes.Add("Attack Boost II");
            enemyTree.Nodes.Add("Attack Boost III");
            enemyTree.Nodes.Add("Defense Boost I");
            enemyTree.Nodes.Add("Defense Boost II");
            enemyTree.Nodes.Add("Defense Boost III");
            enemyTree.Nodes.Add("Element Boost I");
            enemyTree.Nodes.Add("Element Boost II");
            enemyTree.Nodes.Add("Element Boost III");
            enemyTree.Nodes.Add("Serene Journey");
            enemyTree.Nodes.Add("Serene Quest");
            enemyTree.Nodes.Add("Serene Pilgrimage");
            enemyTree.Nodes.Add("Double Link");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Magic Boost I");
            enemyTree.Nodes.Add("Magic Boost II");
            enemyTree.Nodes.Add("Magic Boost III");
            enemyTree.Nodes.Add("HP Boost");
            enemyTree.Nodes.Add("HP Amp");
            enemyTree.Nodes.Add("SP Boost");
            enemyTree.Nodes.Add("SP Amp");
            enemyTree.Nodes.Add("Agility Boost");
            enemyTree.Nodes.Add("Agility Amp");
            enemyTree.Nodes.Add("Resist Fire");
            enemyTree.Nodes.Add("Resist Ice");
            enemyTree.Nodes.Add("Resist Elec");
            enemyTree.Nodes.Add("Resist Wind");
            enemyTree.Nodes.Add("Resist Light");
            enemyTree.Nodes.Add("Resist Dark");
            enemyTree.Nodes.Add("Resist Cut");
            enemyTree.Nodes.Add("Resist Bash");
            enemyTree.Nodes.Add("Resist Stab");
            enemyTree.Nodes.Add("Null Petrify");
            enemyTree.Nodes.Add("Null Sleep");
            enemyTree.Nodes.Add("Null Panic");
            enemyTree.Nodes.Add("Null Poison");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Null Curse");
            enemyTree.Nodes.Add("Null Paralysis");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Keburi no Sue");
            enemyTree.Nodes.Add("Judgement Sword");
            enemyTree.Nodes.Add("Judgement Sword");
            enemyTree.Nodes.Add("Null M-Bind");
            enemyTree.Nodes.Add("Null S-Bind");
            enemyTree.Nodes.Add("Null A-Bind");
            enemyTree.Nodes.Add("Demon's Cut");
            enemyTree.Nodes.Add("Demon's Bash");
            enemyTree.Nodes.Add("Demon's Stab");
            enemyTree.Nodes.Add("God's Cut");
            enemyTree.Nodes.Add("God's Bash");
            enemyTree.Nodes.Add("God's Stab");
            enemyTree.Nodes.Add("SP Recoil");
            enemyTree.Nodes.Add("SP Redeemer");
            enemyTree.Nodes.Add("Start");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("Follow-Up");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("End");
            enemyTree.Nodes.Add("Start");
            enemyTree.Nodes.Add("Medicine");
            enemyTree.Nodes.Add("Oinment");
            enemyTree.Nodes.Add("Antibiotic Gel");
            enemyTree.Nodes.Add("Bead");
            enemyTree.Nodes.Add("Soul Drop");
            enemyTree.Nodes.Add("Snuff Soul");
            enemyTree.Nodes.Add("Chewing Soul");
            enemyTree.Nodes.Add("Soul Food");
            enemyTree.Nodes.Add("Soma Droplet");
            enemyTree.Nodes.Add("Soma Tear");
            enemyTree.Nodes.Add("Revival Bead");
            enemyTree.Nodes.Add("Balm of Life");
            enemyTree.Nodes.Add("Emergency Kit");
            enemyTree.Nodes.Add("Medical Kit");
            enemyTree.Nodes.Add("Mutudi Gem");
            enemyTree.Nodes.Add("Patra Gem");
            enemyTree.Nodes.Add("Purifying Water");
            enemyTree.Nodes.Add("Purifying Salt");
            enemyTree.Nodes.Add("Bravant");
            enemyTree.Nodes.Add("Stonard");
            enemyTree.Nodes.Add("Cut Mist");
            enemyTree.Nodes.Add("Bash Mist");
            enemyTree.Nodes.Add("Stab Mist");
            enemyTree.Nodes.Add("Fire Mist");
            enemyTree.Nodes.Add("Ice Mist");
            enemyTree.Nodes.Add("Elec Mist");
            enemyTree.Nodes.Add("Wind Mist");
            enemyTree.Nodes.Add("Blaze Oil");
            enemyTree.Nodes.Add("Freeze Oil");
            enemyTree.Nodes.Add("Shock Oil");
            enemyTree.Nodes.Add("Cyclone Oil");
            enemyTree.Nodes.Add("San-zun Tama");
            enemyTree.Nodes.Add("Scorching Magatama");
            enemyTree.Nodes.Add("Dry Ice");
            enemyTree.Nodes.Add("Zero Magatama");
            enemyTree.Nodes.Add("Tesla Coil");
            enemyTree.Nodes.Add("Bolt Magatama");
            enemyTree.Nodes.Add("Yashichi");
            enemyTree.Nodes.Add("Storm Magatama");
            enemyTree.Nodes.Add("Segaki Rice");
            enemyTree.Nodes.Add("Curse Paper");
            enemyTree.Nodes.Add("Poison Gas");
            enemyTree.Nodes.Add("Paralysis Gas");
            enemyTree.Nodes.Add("Vanish Ball");
            enemyTree.Nodes.Add("Sleep Gas");
            enemyTree.Nodes.Add("Curse Gas");
            enemyTree.Nodes.Add("Panic Gas");
            enemyTree.Nodes.Add("Analysis Scope");
            enemyTree.Nodes.Add("Homunculus");
            enemyTree.Nodes.Add("Disperse Amulet");
            enemyTree.Nodes.Add("Summon Charm");
            enemyTree.Nodes.Add("Goho-M");
            enemyTree.Nodes.Add("Goba-K");
            enemyTree.Nodes.Add("Winged Sandals");
            enemyTree.Nodes.Add("Sight Beacon");
            enemyTree.Nodes.Add("Soma");
            enemyTree.Nodes.Add("Soma Jelly");
            enemyTree.Nodes.Add("Bead Chain");
            enemyTree.Nodes.Add("Dawn Charm");
            enemyTree.Nodes.Add("Repulse Bell");
            enemyTree.Nodes.Add("Attract Pipe");
            enemyTree.Nodes.Add("Heal Stone");
            enemyTree.Nodes.Add("End");
            enemyTree.Nodes.Add("Ailment Boost");
            enemyTree.Nodes.Add("Ailment Surge");
            enemyTree.Nodes.Add("Raging Fists");
            enemyTree.Nodes.Add("Furious Fists");
            enemyTree.Nodes.Add("Punisher");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Return from Yomi");
            enemyTree.Nodes.Add("Triple Link");
            enemyTree.Nodes.Add("Quadruple Link");
            enemyTree.Nodes.Add("Infinite Link");
            enemyTree.Nodes.Add("Magic Aura");
            enemyTree.Nodes.Add("Skill Boost");
            enemyTree.Nodes.Add("Heroic Spring");
            enemyTree.Nodes.Add("Circle Aura");
            enemyTree.Nodes.Add("Healing Surge");
            enemyTree.Nodes.Add("Stun Recovery");
            enemyTree.Nodes.Add("Overheat");
            enemyTree.Nodes.Add("Overheat End");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("RESERVE");
            enemyTree.Nodes.Add("REVERSE/BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Agi");
            enemyTree.Nodes.Add("Agilao");
            enemyTree.Nodes.Add("Agidyne");
            enemyTree.Nodes.Add("Maragi");
            enemyTree.Nodes.Add("Maragion");
            enemyTree.Nodes.Add("Maragidyne");
            enemyTree.Nodes.Add("Fire Dance");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Garu");
            enemyTree.Nodes.Add("Garula");
            enemyTree.Nodes.Add("Garudyne");
            enemyTree.Nodes.Add("Magaru");
            enemyTree.Nodes.Add("Magarula");
            enemyTree.Nodes.Add("Magarudyne");
            enemyTree.Nodes.Add("Wind Dance");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Bufu");
            enemyTree.Nodes.Add("Bufula");
            enemyTree.Nodes.Add("Bufudyne");
            enemyTree.Nodes.Add("Mabufu");
            enemyTree.Nodes.Add("Mabufula");
            enemyTree.Nodes.Add("Mabufudyne");
            enemyTree.Nodes.Add("Absolute Zero");
            enemyTree.Nodes.Add("Ice Dance");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Zio");
            enemyTree.Nodes.Add("Zionga");
            enemyTree.Nodes.Add("Ziodyne");
            enemyTree.Nodes.Add("Mazio");
            enemyTree.Nodes.Add("Mazionga");
            enemyTree.Nodes.Add("Maziodyne");
            enemyTree.Nodes.Add("Keraunos");
            enemyTree.Nodes.Add("Elec Dance");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Megido");
            enemyTree.Nodes.Add("Megidola");
            enemyTree.Nodes.Add("Megidolaon");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Hama");
            enemyTree.Nodes.Add("Hamaon");
            enemyTree.Nodes.Add("Mahama");
            enemyTree.Nodes.Add("Mahamaon");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Mudo");
            enemyTree.Nodes.Add("Mudoon");
            enemyTree.Nodes.Add("Mamudo");
            enemyTree.Nodes.Add("Mamudoon");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Poisma");
            enemyTree.Nodes.Add("Poison Breath");
            enemyTree.Nodes.Add("Stona");
            enemyTree.Nodes.Add("Stone Mist");
            enemyTree.Nodes.Add("Dormina");
            enemyTree.Nodes.Add("Lullaby Song");
            enemyTree.Nodes.Add("Pulinpa");
            enemyTree.Nodes.Add("Tentarafoo");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Evil Touch");
            enemyTree.Nodes.Add("Evil Smile");
            enemyTree.Nodes.Add("Shibaboo");
            enemyTree.Nodes.Add("Binding Cry");
            enemyTree.Nodes.Add("Makajam");
            enemyTree.Nodes.Add("Silent Song");
            enemyTree.Nodes.Add("Disarm");
            enemyTree.Nodes.Add("Muscle Down");
            enemyTree.Nodes.Add("Scarecrow");
            enemyTree.Nodes.Add("Spiderweb");
            enemyTree.Nodes.Add("Self-Destruct");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Fang Smash");
            enemyTree.Nodes.Add("Kidney Smash");
            enemyTree.Nodes.Add("Cleave");
            enemyTree.Nodes.Add("Twin Slash");
            enemyTree.Nodes.Add("Lunge");
            enemyTree.Nodes.Add("Twin Shot");
            enemyTree.Nodes.Add("Mighty Swing");
            enemyTree.Nodes.Add("Hard Slash");
            enemyTree.Nodes.Add("Charge Shot");
            enemyTree.Nodes.Add("Stab Shower");
            enemyTree.Nodes.Add("Frost Edge");
            enemyTree.Nodes.Add("Guillotine");
            enemyTree.Nodes.Add("Tempest Slash");
            enemyTree.Nodes.Add("Lightning Smash");
            enemyTree.Nodes.Add("Drain Touch");
            enemyTree.Nodes.Add("Gigantic Fist");
            enemyTree.Nodes.Add("Single Shot");
            enemyTree.Nodes.Add("Thorn Shackles");
            enemyTree.Nodes.Add("Thorn Cuffs");
            enemyTree.Nodes.Add("Thorn Chains");
            enemyTree.Nodes.Add("Assault Shot");
            enemyTree.Nodes.Add("Primal Force");
            enemyTree.Nodes.Add("Heavy Shot");
            enemyTree.Nodes.Add("Broadshot");
            enemyTree.Nodes.Add("Myriad Arrows");
            enemyTree.Nodes.Add("Megaton Press");
            enemyTree.Nodes.Add("Brain Shake");
            enemyTree.Nodes.Add("Stardrop");
            enemyTree.Nodes.Add("Buchikamashi");
            enemyTree.Nodes.Add("Spin Slash");
            enemyTree.Nodes.Add("Blade of Fury");
            enemyTree.Nodes.Add("Tousatsujin");
            enemyTree.Nodes.Add("Vorpal Blade");
            enemyTree.Nodes.Add("Crazed Slash");
            enemyTree.Nodes.Add("Skull Cracker");
            enemyTree.Nodes.Add("Scorching Blast");
            enemyTree.Nodes.Add("Heat Wave");
            enemyTree.Nodes.Add("Megaton Slam");
            enemyTree.Nodes.Add("Megaton Slam");
            enemyTree.Nodes.Add("Blinding Slice");
            enemyTree.Nodes.Add("Toxic Slice");
            enemyTree.Nodes.Add("Dream Slice");
            enemyTree.Nodes.Add("Stunning Slice");
            enemyTree.Nodes.Add("Bane Slice");
            enemyTree.Nodes.Add("Mow Down");
            enemyTree.Nodes.Add("Deathbound");
            enemyTree.Nodes.Add("Torrent Shot");
            enemyTree.Nodes.Add("Rampage");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Dia");
            enemyTree.Nodes.Add("Diarama");
            enemyTree.Nodes.Add("Diarahan");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Media");
            enemyTree.Nodes.Add("Mediarama");
            enemyTree.Nodes.Add("Mediarahan");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Samarecarm");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Patra");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Mutudi");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Bestial Roar");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Rampart");
            enemyTree.Nodes.Add("Safeguard");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Life Wall");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Matarukaja");
            enemyTree.Nodes.Add("Marakukaja");
            enemyTree.Nodes.Add("Masukukaja");
            enemyTree.Nodes.Add("Power Charge");
            enemyTree.Nodes.Add("Mind Charge");
            enemyTree.Nodes.Add("Fire Corrosion");
            enemyTree.Nodes.Add("Ice Corrosion");
            enemyTree.Nodes.Add("Elec Corrosion");
            enemyTree.Nodes.Add("Wind Corrosion");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Matarunda");
            enemyTree.Nodes.Add("Marakunda");
            enemyTree.Nodes.Add("Masukunda");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Dekaja");
            enemyTree.Nodes.Add("Dekunda");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Escape");
            enemyTree.Nodes.Add("");
            enemyTree.Nodes.Add("");
            enemyTree.Nodes.Add("Tarukaja");
            enemyTree.Nodes.Add("Rakukaja");
            enemyTree.Nodes.Add("Sukukaja");
            enemyTree.Nodes.Add("Tarunda");
            enemyTree.Nodes.Add("Rakunda");
            enemyTree.Nodes.Add("Sukunda");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Fire Boost");
            enemyTree.Nodes.Add("Ice Boost");
            enemyTree.Nodes.Add("Elec Boost");
            enemyTree.Nodes.Add("Wind Boost");
            enemyTree.Nodes.Add("Trick Step");
            enemyTree.Nodes.Add("Recovery Up");
            enemyTree.Nodes.Add("Phys Boost");
            enemyTree.Nodes.Add("Phys Boost II");
            enemyTree.Nodes.Add("Magic Boost");
            enemyTree.Nodes.Add("Magic Boost II");
            enemyTree.Nodes.Add("Wide Effect");
            enemyTree.Nodes.Add("Wide Effect II");
            enemyTree.Nodes.Add("Wide Effect III");
            enemyTree.Nodes.Add("Double Action");
            enemyTree.Nodes.Add("Double Action II");
            enemyTree.Nodes.Add("Double Action III");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Soldier Summon");
            enemyTree.Nodes.Add("Reinforcements");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Holy Wrath");
            enemyTree.Nodes.Add("Vow");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Drastic Measure");
            enemyTree.Nodes.Add("Endure");
            enemyTree.Nodes.Add("Rabbit's Foot");
            enemyTree.Nodes.Add("Deafening Roar");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("Gears of Time");
            enemyTree.Nodes.Add("Time Warp");
            enemyTree.Nodes.Add("Death Sentence");
            enemyTree.Nodes.Add("Time Reversal");
            enemyTree.Nodes.Add("Time Stop");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("All-Out Attack");
            enemyTree.Nodes.Add("Megidolaon");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");
            enemyTree.Nodes.Add("BLANK");

            TreeNodeCollection nodeCollect = enemyTree.Nodes;
            enemyTree.SelectedNode = nodeCollect[0];
        }

        private void FormQSkillEditor_Load(object sender, EventArgs e)
        {

        }

        private void enemyTree_AfterSelect(object sender, TreeViewEventArgs e)
        {

            //Value 1 is distance / offset from the start of the file to the start of the array ("Start" in 010) (The first byte is 0) 
            //Value 2 is how many bytes / hexes are in a "row"   (First byte is 1 NOT 0)
            //Value 3 is how many bytes into the row info starts (The first byte is byte 0)

            richTextBoxMaxLv.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 0).ToString("D");
            richTextBoxSkillType.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 2).ToString("D");  
            richTextBoxBindType.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 4).ToString("D");

            richTextBox4.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 6].ToString("D");
            richTextBoxRange.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 7].ToString("D");
            richTextBoxTargetType.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 8].ToString("D");

            richTextBoxTargetTeam.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 9].ToString("D");
            richTextBoxAvailability.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 10].ToString("D");
            richTextBox9.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 11].ToString("D");
            richTextBox10.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 12].ToString("D");

            richTextBox11.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 16).ToString("D");

            richTextBox12.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 19].ToString("D");
            richTextBoxElement.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 20).ToString("D");
            richTextBox14.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 22].ToString("D");
            richTextBox15.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 23].ToString("D");

            richTextBoxInflictCheck.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 24).ToString("D");
            richTextBoxAilments.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 26).ToString("D");

            

            richTextBox28.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 28].ToString("D");
            richTextBox29.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 29].ToString("D");
            richTextBox30.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 30].ToString("D");
            richTextBox31.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 31].ToString("D");
            richTextBox32.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 32].ToString("D");

            richTextBox33.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 33].ToString("D");
            richTextBox36.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 36].ToString("D");









        }

        private void buttonSave_Click(object sender, EventArgs e) //Save Button
        {
            //B! .TryParse(Name! .Text, out type! value! ); { Form1.ByteWriter( value! , enemydata_array, StartingHex! + (treeView1.SelectedNode.Index * RowSize! ) + ArrayOfset! ); }
            //B=Byte size, 1="Byte" 2="UInt16" 4="UInt32"         Name!=the name of the textbox        type!= byte / ushort / uint, only include this in the FIRST time this ever happens in a form, later copies ommit this!
            //value!=Name of variable that holds the byte type (so byte/short/int has diffrent names)       StartingHex!= The hex offset      RowSize!=How many bytes in a row    Arrayofset! = how far into the row do we start grabbing info or saving it
            
            UInt16.TryParse(richTextBoxMaxLv.Text, out ushort value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 0); } //First 2 byte save
            UInt16.TryParse(richTextBoxSkillType.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 2); } 
            UInt16.TryParse(richTextBoxBindType.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 4); } 
            
            Byte.TryParse(richTextBox4.Text, out byte value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 6); } //First 1 byte save
            Byte.TryParse(richTextBoxRange.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 7); }
            Byte.TryParse(richTextBoxTargetType.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 8); }
            Byte.TryParse(richTextBoxTargetTeam.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 9); }
            Byte.TryParse(richTextBoxAvailability.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 10); }
            Byte.TryParse(richTextBox9.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 11); }
            Byte.TryParse(richTextBox10.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 12); }

            UInt16.TryParse(richTextBox11.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 16); }
            
            Byte.TryParse(richTextBox12.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 19); }
            UInt16.TryParse(richTextBoxElement.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 20); }
            Byte.TryParse(richTextBox14.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 22); }
            Byte.TryParse(richTextBox15.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 23); }

            UInt16.TryParse(richTextBoxInflictCheck.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 24); }
            UInt16.TryParse(richTextBoxAilments.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 26); }

            Byte.TryParse(richTextBox28.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 28); }
            Byte.TryParse(richTextBox29.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 29); }
            Byte.TryParse(richTextBox30.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 30); }
            Byte.TryParse(richTextBox31.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 31); }
            Byte.TryParse(richTextBox32.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 32); }

            Byte.TryParse(richTextBox33.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 33); }
            Byte.TryParse(richTextBox36.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 36); }
            
            

            File.WriteAllBytes(Properties.Settings.Default.PQRomFS + "\\battle\\table\\skilltable.tbl", enemydata_array); //saves to the path i set, everything in the array/
        }
    }
}
