using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using System.Diagnostics;
using Microsoft.Win32;
using Microsoft.WindowsAPICodePack.Dialogs;

namespace Etrian_Odyssey_IV_test
{
    public partial class FormQSkillEditor : Form
    {
        String treeloaded = "No";
        List<ComboBox> boxes = new List<ComboBox>();  //Puts the combo boxes in an array called boxes so i can refernce this array later (to make the code pretty and save time)
        byte[] enemydata_array; //This starts the array, the name after is what i name this array?
        public FormQSkillEditor()
        {
            InitializeComponent();
            boxes.Add(comboBoxSkillFlag1);
            boxes.Add(comboBoxSkillFlag2);
            boxes.Add(comboBoxSkillFlag3);
            boxes.Add(comboBoxSkillFlag4);
            boxes.Add(comboBoxSkillFlag5);
            boxes.Add(comboBoxSkillFlag6);
            boxes.Add(comboBoxSkillFlag7);
            boxes.Add(comboBoxSkillFlag8);

            string enemydata_path = Properties.Settings.Default.PQRomFS + "\\battle\\table\\skilltable.tbl"; //This defines the path as a string, so i can refer to it by this string/name instead of the full path every time
            int enemydata_length = (int)(new FileInfo(enemydata_path).Length);   //The leagth of the array?
            enemydata_array = File.ReadAllBytes(enemydata_path);  //loads an array with whatever is in the path

            //Add the EO1 enemy list to the in editor list of enemy names
            enemyTree.Nodes.Add("4096 BLANK");
            enemyTree.Nodes.Add("4097 Attack");
            enemyTree.Nodes.Add("4098 Agi");
            enemyTree.Nodes.Add("4099 Agilao");
            enemyTree.Nodes.Add("4100 Agidyne");
            enemyTree.Nodes.Add("4101 Maragi");
            enemyTree.Nodes.Add("4102 Maragion");
            enemyTree.Nodes.Add("4103 Maragidyne");
            enemyTree.Nodes.Add("4104 Fire Spray");
            enemyTree.Nodes.Add("4105 Ragnarok");
            enemyTree.Nodes.Add("4106 BLANK");
            enemyTree.Nodes.Add("4107 BLANK");
            enemyTree.Nodes.Add("4108 BLANK");
            enemyTree.Nodes.Add("4109 BLANK");
            enemyTree.Nodes.Add("4110 Garu");
            enemyTree.Nodes.Add("4111 Garula");
            enemyTree.Nodes.Add("4112 Garudyne");
            enemyTree.Nodes.Add("4113 Magaru");
            enemyTree.Nodes.Add("4114 Magarula");
            enemyTree.Nodes.Add("4115 Magarudyne");
            enemyTree.Nodes.Add("4116 Cyclone");
            enemyTree.Nodes.Add("4117 Panta Rhei");
            enemyTree.Nodes.Add("4118 BLANK");
            enemyTree.Nodes.Add("4119 BLANK");
            enemyTree.Nodes.Add("4120 BLANK");
            enemyTree.Nodes.Add("4121 BLANK");
            enemyTree.Nodes.Add("4122 Bufu");
            enemyTree.Nodes.Add("4123 Bufula");
            enemyTree.Nodes.Add("4124 Bufudyne");
            enemyTree.Nodes.Add("4125 Mabufu");
            enemyTree.Nodes.Add("4126 Mabufula");
            enemyTree.Nodes.Add("4127 Mabufudyne");
            enemyTree.Nodes.Add("4128 Icy Paradise");
            enemyTree.Nodes.Add("4129 Niflheim");
            enemyTree.Nodes.Add("4130 Frozen Spear");
            enemyTree.Nodes.Add("4131 BLANK");
            enemyTree.Nodes.Add("4132 BLANK");
            enemyTree.Nodes.Add("4133 BLANK");
            enemyTree.Nodes.Add("4134 BLANK");
            enemyTree.Nodes.Add("4135 Zio");
            enemyTree.Nodes.Add("4136 Zionga");
            enemyTree.Nodes.Add("4137 Ziodyne");
            enemyTree.Nodes.Add("4138 Mazio");
            enemyTree.Nodes.Add("4139 Mazionga");
            enemyTree.Nodes.Add("4140 Maziodyne");
            enemyTree.Nodes.Add("4141 BLANK");
            enemyTree.Nodes.Add("4142 Thunder Reign");
            enemyTree.Nodes.Add("4143 Keraunos");
            enemyTree.Nodes.Add("4144 Thunder Clap");
            enemyTree.Nodes.Add("4145 BLANK");
            enemyTree.Nodes.Add("4146 BLANK");
            enemyTree.Nodes.Add("4147 Megido");
            enemyTree.Nodes.Add("4148 Megidola");
            enemyTree.Nodes.Add("4149 Megidolaon");
            enemyTree.Nodes.Add("4150 BLANK");
            enemyTree.Nodes.Add("4151 Black Viper");
            enemyTree.Nodes.Add("4152 Morning Star");
            enemyTree.Nodes.Add("4153 BLANK");
            enemyTree.Nodes.Add("4154 BLANK");
            enemyTree.Nodes.Add("4155 BLANK");
            enemyTree.Nodes.Add("4156 BLANK");
            enemyTree.Nodes.Add("4157 Hama");
            enemyTree.Nodes.Add("4158 Hamaon");
            enemyTree.Nodes.Add("4159 Mahama");
            enemyTree.Nodes.Add("4160 Mahamaon");
            enemyTree.Nodes.Add("4161 BLANK");
            enemyTree.Nodes.Add("4162 BLANK");
            enemyTree.Nodes.Add("4163 Samsara");
            enemyTree.Nodes.Add("4164 BLANK");
            enemyTree.Nodes.Add("4165 BLANK");
            enemyTree.Nodes.Add("4166 BLANK");
            enemyTree.Nodes.Add("4167 BLANK");
            enemyTree.Nodes.Add("4168 Mudo");
            enemyTree.Nodes.Add("4169 Mudoon");
            enemyTree.Nodes.Add("4170 Mamudo");
            enemyTree.Nodes.Add("4171 Mamudoon");
            enemyTree.Nodes.Add("4172 BLANK");
            enemyTree.Nodes.Add("4173 BLANK");
            enemyTree.Nodes.Add("4174 Die For Me!");
            enemyTree.Nodes.Add("4175 BLANK");
            enemyTree.Nodes.Add("4176 BLANK");
            enemyTree.Nodes.Add("4177 BLANK");
            enemyTree.Nodes.Add("4178 BLANK");
            enemyTree.Nodes.Add("4179 Pulinpa");
            enemyTree.Nodes.Add("4180 Tentarafoo");
            enemyTree.Nodes.Add("4181 Poisma");
            enemyTree.Nodes.Add("4182 Poison Breath");
            enemyTree.Nodes.Add("4183 Gambit");
            enemyTree.Nodes.Add("4184 Flashbang");
            enemyTree.Nodes.Add("4185 Dormina");
            enemyTree.Nodes.Add("4186 Lullaby Song");
            enemyTree.Nodes.Add("4187 Evil Touch");
            enemyTree.Nodes.Add("4188 Evil Smile");
            enemyTree.Nodes.Add("4189 BLANK");
            enemyTree.Nodes.Add("4190 BLANK");
            enemyTree.Nodes.Add("4191 Heavy Gi");
            enemyTree.Nodes.Add("4192 Bracer of Might");
            enemyTree.Nodes.Add("4193 Sacrificial Idol");
            enemyTree.Nodes.Add("4194 Rudra Ring");
            enemyTree.Nodes.Add("4195 Chakra Ring");
            enemyTree.Nodes.Add("4196 Willow Wing");
            enemyTree.Nodes.Add("4197 Snowy Wing");
            enemyTree.Nodes.Add("4198 Enduring Wing");
            enemyTree.Nodes.Add("4199 Blazing Flame");
            enemyTree.Nodes.Add("4200 Frozen Stone");
            enemyTree.Nodes.Add("4201 Storm Ring");
            enemyTree.Nodes.Add("4202 Lightning Gloves");
            enemyTree.Nodes.Add("4203 Radiant Halo");
            enemyTree.Nodes.Add("4204 Ring of Darkness");
            enemyTree.Nodes.Add("4205 Bladed Plume");
            enemyTree.Nodes.Add("4206 Iron Pendant");
            enemyTree.Nodes.Add("4207 Helmet");
            enemyTree.Nodes.Add("4208 Omnipotent Orb");
            enemyTree.Nodes.Add("4209 BLANK");
            enemyTree.Nodes.Add("4210 Germanium Ring");
            enemyTree.Nodes.Add("4211 Scapegoat");
            enemyTree.Nodes.Add("4212 Body-Soul Reverse");
            enemyTree.Nodes.Add("4213 St-Ma Reverse");
            enemyTree.Nodes.Add("4214 St-En Reverse");
            enemyTree.Nodes.Add("4215 St-Ag Reverse");
            enemyTree.Nodes.Add("4216 St-Lu Reverse");
            enemyTree.Nodes.Add("4217 Ma-En Reverse");
            enemyTree.Nodes.Add("4218 Ma-Ag Reverse");
            enemyTree.Nodes.Add("4219 Ma-Lu Reverse");
            enemyTree.Nodes.Add("4220 En-Ag Reverse");
            enemyTree.Nodes.Add("4221 En-Lu Reverse");
            enemyTree.Nodes.Add("4222 Ag-Lu Reverse");
            enemyTree.Nodes.Add("4223 BLANK");
            enemyTree.Nodes.Add("4224 Physical Start");
            enemyTree.Nodes.Add("4225 Fang Smash");
            enemyTree.Nodes.Add("4226 Kidney Smash");
            enemyTree.Nodes.Add("4227 Cleave");
            enemyTree.Nodes.Add("4228 Twin Slash");
            enemyTree.Nodes.Add("4229 End Shot");
            enemyTree.Nodes.Add("4230 Double Shot");
            enemyTree.Nodes.Add("4231 Mighty Swing");
            enemyTree.Nodes.Add("4232 Fatal End");
            enemyTree.Nodes.Add("4233 Silent Thrust");
            enemyTree.Nodes.Add("4234 Swift Strike");
            enemyTree.Nodes.Add("4235 Frost Edge");
            enemyTree.Nodes.Add("4236 Zanshinken");
            enemyTree.Nodes.Add("4237 Zanshin Strike");
            enemyTree.Nodes.Add("4238 Death Needle");
            enemyTree.Nodes.Add("4239 Guillotine");
            enemyTree.Nodes.Add("4240 Tempest Slash");
            enemyTree.Nodes.Add("4241 Bolt Strike");
            enemyTree.Nodes.Add("4242 Holy Touch");
            enemyTree.Nodes.Add("4243 Revenge Blow");
            enemyTree.Nodes.Add("4244 Revenge Strike");
            enemyTree.Nodes.Add("4245 Gigantic Fist");
            enemyTree.Nodes.Add("4246 Single Shot");
            enemyTree.Nodes.Add("4247 Scarecrow");
            enemyTree.Nodes.Add("4248 Disarm");
            enemyTree.Nodes.Add("4249 Makajam");
            enemyTree.Nodes.Add("4250 Assault Shot");
            enemyTree.Nodes.Add("4251 Primal Force");
            enemyTree.Nodes.Add("4252 Heavy Shot");
            enemyTree.Nodes.Add("4253 Broadshot");
            enemyTree.Nodes.Add("4254 Myriad Arrows");
            enemyTree.Nodes.Add("4255 Punishment");
            enemyTree.Nodes.Add("4256 Assault Dive");
            enemyTree.Nodes.Add("4257 Sleeper Punch");
            enemyTree.Nodes.Add("4258 Teardrop");
            enemyTree.Nodes.Add("4259 Buchikamashi");
            enemyTree.Nodes.Add("4260 Deathbound");
            enemyTree.Nodes.Add("4261 Blade of Fury");
            enemyTree.Nodes.Add("4262 Glacial Edge");
            enemyTree.Nodes.Add("4263 Vorpal Blade");
            enemyTree.Nodes.Add("4264 Danse Macabre");
            enemyTree.Nodes.Add("4265 Skull Cracker");
            enemyTree.Nodes.Add("4266 Fusion Blast");
            enemyTree.Nodes.Add("4267 Heat Wave");
            enemyTree.Nodes.Add("4268 Light Wave");
            enemyTree.Nodes.Add("4269 Paralysis");
            enemyTree.Nodes.Add("4270 Brutal Slash");
            enemyTree.Nodes.Add("4271 Photon Edge");
            enemyTree.Nodes.Add("4272 Prana");
            enemyTree.Nodes.Add("4273 Heaven's Blade");
            enemyTree.Nodes.Add("4274 God's Hand");
            enemyTree.Nodes.Add("4275 Angelic Trumpet");
            enemyTree.Nodes.Add("4276 Hassou Tobi");
            enemyTree.Nodes.Add("4277 Hailstorm");
            enemyTree.Nodes.Add("4278 Arrow Rain");
            enemyTree.Nodes.Add("4279 Aeon Rain");
            enemyTree.Nodes.Add("4280 Blinding Slice");
            enemyTree.Nodes.Add("4281 Toxic Slice");
            enemyTree.Nodes.Add("4282 Dream Slice");
            enemyTree.Nodes.Add("4283 Stunning Slice");
            enemyTree.Nodes.Add("4284 Bane Slice");
            enemyTree.Nodes.Add("4285 Gurentou");
            enemyTree.Nodes.Add("4286 Tousatsujin");
            enemyTree.Nodes.Add("4287 Raikouzan");
            enemyTree.Nodes.Add("4288 Jinpugeki");
            enemyTree.Nodes.Add("4289 Shinkuuha");
            enemyTree.Nodes.Add("4290 Resseiha");
            enemyTree.Nodes.Add("4291 Pralaya");
            enemyTree.Nodes.Add("4292 Shadow Run");
            enemyTree.Nodes.Add("4293 World's End");
            enemyTree.Nodes.Add("4294 Raimeizan");
            enemyTree.Nodes.Add("4295 Raijinzan");
            enemyTree.Nodes.Add("4296 Gokuentou");
            enemyTree.Nodes.Add("4297 Hientou");
            enemyTree.Nodes.Add("4298 Reppu Strike");
            enemyTree.Nodes.Add("4299 Kamikaze Strike");
            enemyTree.Nodes.Add("4300 Hex Slice");
            enemyTree.Nodes.Add("4301 Soul Slice");
            enemyTree.Nodes.Add("4302 BLANK");
            enemyTree.Nodes.Add("4303 Physical End");
            enemyTree.Nodes.Add("4304 Support Start");
            enemyTree.Nodes.Add("4305 Dia");
            enemyTree.Nodes.Add("4306 Diarama");
            enemyTree.Nodes.Add("4307 Diarahan");
            enemyTree.Nodes.Add("4308 Recovery");
            enemyTree.Nodes.Add("4309 Life Goblet");
            enemyTree.Nodes.Add("4310 Media");
            enemyTree.Nodes.Add("4311 Mediarama");
            enemyTree.Nodes.Add("4312 Mediarahan");
            enemyTree.Nodes.Add("4313 Recarm");
            enemyTree.Nodes.Add("4314 Samarecarm");
            enemyTree.Nodes.Add("4315 Treatment");
            enemyTree.Nodes.Add("4316 Renewal");
            enemyTree.Nodes.Add("4317 Patra");
            enemyTree.Nodes.Add("4318 Refresh");
            enemyTree.Nodes.Add("4319 Me Patra");
            enemyTree.Nodes.Add("4320 Mutudi");
            enemyTree.Nodes.Add("4321 Becalm");
            enemyTree.Nodes.Add("4322 Mamutudi");
            enemyTree.Nodes.Add("4323 Amrita");
            enemyTree.Nodes.Add("4324 BLANK");
            enemyTree.Nodes.Add("4325 BLANK");
            enemyTree.Nodes.Add("4326 Bestial Roar");
            enemyTree.Nodes.Add("4327 Dragon Cry");
            enemyTree.Nodes.Add("4328 Improved Link");
            enemyTree.Nodes.Add("4329 Master Link");
            enemyTree.Nodes.Add("4330 Shadow Cloak");
            enemyTree.Nodes.Add("4331 Rampart");
            enemyTree.Nodes.Add("4332 Pain-Eater");
            enemyTree.Nodes.Add("4333 Safeguard");
            enemyTree.Nodes.Add("4334 Body Shield");
            enemyTree.Nodes.Add("4335 Life Wall");
            enemyTree.Nodes.Add("4336 True Warden");
            enemyTree.Nodes.Add("4337 Holy Blessing");
            enemyTree.Nodes.Add("4338 Guiding Sword");
            enemyTree.Nodes.Add("4339 Guarding Staff");
            enemyTree.Nodes.Add("4340 Spotter");
            enemyTree.Nodes.Add("4341 Critical Eye");
            enemyTree.Nodes.Add("4342 Makara Boost");
            enemyTree.Nodes.Add("4343 Matarukaja");
            enemyTree.Nodes.Add("4344 Marakukaja");
            enemyTree.Nodes.Add("4345 Masukukaja");
            enemyTree.Nodes.Add("4346 Power Charge");
            enemyTree.Nodes.Add("4347 Mind Charge");
            enemyTree.Nodes.Add("4348 Fire Blessing");
            enemyTree.Nodes.Add("4349 Ice Blessing");
            enemyTree.Nodes.Add("4350 Elec Blessing");
            enemyTree.Nodes.Add("4351 Wind Blessing");
            enemyTree.Nodes.Add("4352 Quick Order");
            enemyTree.Nodes.Add("4353 Daunting Stare");
            enemyTree.Nodes.Add("4354 Piercing Stare");
            enemyTree.Nodes.Add("4355 Tetra Down");
            enemyTree.Nodes.Add("4356 Makara Down");
            enemyTree.Nodes.Add("4357 Matarunda");
            enemyTree.Nodes.Add("4358 Marakunda");
            enemyTree.Nodes.Add("4359 Masukunda");
            enemyTree.Nodes.Add("4360 Rear Guard");
            enemyTree.Nodes.Add("4361 BLANK");
            enemyTree.Nodes.Add("4362 BLANK");
            enemyTree.Nodes.Add("4363 BLANK");
            enemyTree.Nodes.Add("4364 Stagnant Air");
            enemyTree.Nodes.Add("4365 Salome's Kiss");
            enemyTree.Nodes.Add("4366 BLANK");
            enemyTree.Nodes.Add("4367 BLANK");
            enemyTree.Nodes.Add("4368 BLANK");
            enemyTree.Nodes.Add("4369 Dekaja");
            enemyTree.Nodes.Add("4370 Dekunda");
            enemyTree.Nodes.Add("4371 Heat Sink");
            enemyTree.Nodes.Add("4372 Makatora");
            enemyTree.Nodes.Add("4373 Decoy Sign");
            enemyTree.Nodes.Add("4374 Fire Wall");
            enemyTree.Nodes.Add("4375 Wind Wall");
            enemyTree.Nodes.Add("4376 Ice Wall");
            enemyTree.Nodes.Add("4377 Elec Wall");
            enemyTree.Nodes.Add("4378 Light Wall");
            enemyTree.Nodes.Add("4379 Dark Wall");
            enemyTree.Nodes.Add("4380 Tarukaja");
            enemyTree.Nodes.Add("4381 Rakukaja");
            enemyTree.Nodes.Add("4382 Sukukaja");
            enemyTree.Nodes.Add("4383 Tarunda");
            enemyTree.Nodes.Add("4384 Rakunda");
            enemyTree.Nodes.Add("4385 Sukunda");
            enemyTree.Nodes.Add("4386 Debilitate");
            enemyTree.Nodes.Add("4387 Heat Riser");
            enemyTree.Nodes.Add("4388 Mind's Eye");
            enemyTree.Nodes.Add("4389 Door of Hades");
            enemyTree.Nodes.Add("4390 Call to Hades");
            enemyTree.Nodes.Add("4391 Calamity Seed");
            enemyTree.Nodes.Add("4392 Calamity Advent");
            enemyTree.Nodes.Add("4393 Lunar Blessing");
            enemyTree.Nodes.Add("4394 BLANK");
            enemyTree.Nodes.Add("4395 Healing Harp");
            enemyTree.Nodes.Add("4396 Healing Harp");
            enemyTree.Nodes.Add("4397 Lightning Smash");
            enemyTree.Nodes.Add("4398 Thunder Smash");
            enemyTree.Nodes.Add("4399 Scorching Blast");
            enemyTree.Nodes.Add("4400 Nuclear Blast");
            enemyTree.Nodes.Add("4401 Sonic Punch");
            enemyTree.Nodes.Add("4402 Brain Shake");
            enemyTree.Nodes.Add("4403 Moondrop");
            enemyTree.Nodes.Add("4404 Stardrop");
            enemyTree.Nodes.Add("4405 BLANK");
            enemyTree.Nodes.Add("4406 BLANK");
            enemyTree.Nodes.Add("4407 BLANK");
            enemyTree.Nodes.Add("4408 BLANK");
            enemyTree.Nodes.Add("4409 BLANK");
            enemyTree.Nodes.Add("4410 BLANK");
            enemyTree.Nodes.Add("4411 BLANK");
            enemyTree.Nodes.Add("4412 BLANK");
            enemyTree.Nodes.Add("4413 BLANK");
            enemyTree.Nodes.Add("4414 BLANK");
            enemyTree.Nodes.Add("4415 Support End");
            enemyTree.Nodes.Add("4416 Leader Start");
            enemyTree.Nodes.Add("4417 All-Out Attack");
            enemyTree.Nodes.Add("4418 Sutakora Foot");
            enemyTree.Nodes.Add("4419 Analyze");
            enemyTree.Nodes.Add("4420 Full Analysis");
            enemyTree.Nodes.Add("4421 Snake Glare");
            enemyTree.Nodes.Add("4422 Heroic Wind");
            enemyTree.Nodes.Add("4423 BLANK");
            enemyTree.Nodes.Add("4424 BLANK");
            enemyTree.Nodes.Add("4425 BLANK");
            enemyTree.Nodes.Add("4426 BLANK");
            enemyTree.Nodes.Add("4427 Harvest Prayer");
            enemyTree.Nodes.Add("4428 Cornucopia");
            enemyTree.Nodes.Add("4429 Healing Tide");
            enemyTree.Nodes.Add("4430 Healing Tide");
            enemyTree.Nodes.Add("4431 Renewal Ray");
            enemyTree.Nodes.Add("4432 Renewal Aura");
            enemyTree.Nodes.Add("4433 Healing Breeze");
            enemyTree.Nodes.Add("4434 Spotlight");
            enemyTree.Nodes.Add("4435 Yomi Return");
            enemyTree.Nodes.Add("4436 Third Eye");
            enemyTree.Nodes.Add("4437 Orb of Resolve");
            enemyTree.Nodes.Add("4438 Orb of Power");
            enemyTree.Nodes.Add("4439 Orb of Haste");
            enemyTree.Nodes.Add("4440 Life Aid");
            enemyTree.Nodes.Add("4441 Victory Cry");
            enemyTree.Nodes.Add("4442 Safety Prayer");
            enemyTree.Nodes.Add("4443 Calming Lull");
            enemyTree.Nodes.Add("4444 Spotter");
            enemyTree.Nodes.Add("4445 Magic Mallet");
            enemyTree.Nodes.Add("4446 Fanfare");
            enemyTree.Nodes.Add("4447 Into the Void");
            enemyTree.Nodes.Add("4448 Tidal Wave");
            enemyTree.Nodes.Add("4449 Oracle");
            enemyTree.Nodes.Add("4450 Oracle");
            enemyTree.Nodes.Add("4451 Oracle");
            enemyTree.Nodes.Add("4452 Oracle");
            enemyTree.Nodes.Add("4453 Oracle");
            enemyTree.Nodes.Add("4454 Oracle");
            enemyTree.Nodes.Add("4455 Healing Breeze");
            enemyTree.Nodes.Add("4456 Absolute Camera");
            enemyTree.Nodes.Add("4457 Prayer");
            enemyTree.Nodes.Add("4458 Vigilant Sonar");
            enemyTree.Nodes.Add("4459 Treasure Hunter");
            enemyTree.Nodes.Add("4460 Fortune Hunter");
            enemyTree.Nodes.Add("4461 Faerie's Vigil");
            enemyTree.Nodes.Add("4462 Tengu's Vigil");
            enemyTree.Nodes.Add("4463 Clairvoyance");
            enemyTree.Nodes.Add("4464 Farsight");
            enemyTree.Nodes.Add("4465 Purifying Rain");
            enemyTree.Nodes.Add("4466 Material Cache");
            enemyTree.Nodes.Add("4467 Zero Set");
            enemyTree.Nodes.Add("4468 Eternal Melody");
            enemyTree.Nodes.Add("4469 Lavish Gift");
            enemyTree.Nodes.Add("4470 Holy Gift");
            enemyTree.Nodes.Add("4471 BLANK");
            enemyTree.Nodes.Add("4472 BLANK");
            enemyTree.Nodes.Add("4473 Hunting Prayer");
            enemyTree.Nodes.Add("4474 Endless Bounty");
            enemyTree.Nodes.Add("4475 BLANK");
            enemyTree.Nodes.Add("4476 Alleys of Light");
            enemyTree.Nodes.Add("4477 Paths of Light");
            enemyTree.Nodes.Add("4478 Roads of Light");
            enemyTree.Nodes.Add("4479 BLANK");
            enemyTree.Nodes.Add("4480 Start");
            enemyTree.Nodes.Add("4481 Stun Circle");
            enemyTree.Nodes.Add("4482 Magic Circle");
            enemyTree.Nodes.Add("4483 Sleep Circle");
            enemyTree.Nodes.Add("4484 Magic Circle");
            enemyTree.Nodes.Add("4485 Poison Circle");
            enemyTree.Nodes.Add("4486 Magic Circle");
            enemyTree.Nodes.Add("4487 Panic Circle");
            enemyTree.Nodes.Add("4488 Magic Circle");
            enemyTree.Nodes.Add("4489 Silence Circle");
            enemyTree.Nodes.Add("4490 Magic Circle");
            enemyTree.Nodes.Add("4491 Decay Circle");
            enemyTree.Nodes.Add("4492 Magic Circle");
            enemyTree.Nodes.Add("4493 Lethargy Circle");
            enemyTree.Nodes.Add("4494 Magic Circle");
            enemyTree.Nodes.Add("4495 Summon Ghost");
            enemyTree.Nodes.Add("4496 Summon Demon");
            enemyTree.Nodes.Add("4497 Shura Tensei");
            enemyTree.Nodes.Add("4498 Shura Revert");
            enemyTree.Nodes.Add("4499 Shura Instincts");
            enemyTree.Nodes.Add("4500 Orgia Mode");
            enemyTree.Nodes.Add("4501 Mode Disengage");
            enemyTree.Nodes.Add("4502 Heal Memento");
            enemyTree.Nodes.Add("4503 Heal Memento");
            enemyTree.Nodes.Add("4504 Free Memento");
            enemyTree.Nodes.Add("4505 Free Memento");
            enemyTree.Nodes.Add("4506 Pure Memento");
            enemyTree.Nodes.Add("4507 Pure Memento");
            enemyTree.Nodes.Add("4508 Blessing of Relief");
            enemyTree.Nodes.Add("4509 Death Counter");
            enemyTree.Nodes.Add("4510 Death Counter");
            enemyTree.Nodes.Add("4511 Death Chaser");
            enemyTree.Nodes.Add("4512 Death Chaser");
            enemyTree.Nodes.Add("4513 Fierce Stance");
            enemyTree.Nodes.Add("4514 Fierce Stance");
            enemyTree.Nodes.Add("4515 Ferocious Stance");
            enemyTree.Nodes.Add("4516 Guard Stance");
            enemyTree.Nodes.Add("4517 Healing Step");
            enemyTree.Nodes.Add("4518 Wide Dance");
            enemyTree.Nodes.Add("4519 Rush Dance");
            enemyTree.Nodes.Add("4520 BLANK");
            enemyTree.Nodes.Add("4521 Flame Link");
            enemyTree.Nodes.Add("4522 Flame Link");
            enemyTree.Nodes.Add("4523 Frost Link");
            enemyTree.Nodes.Add("4524 Frost Link");
            enemyTree.Nodes.Add("4525 Bolt Link");
            enemyTree.Nodes.Add("4526 Bolt Link");
            enemyTree.Nodes.Add("4527 Gale Link");
            enemyTree.Nodes.Add("4528 Gale Link");
            enemyTree.Nodes.Add("4529 Pain Watcher");
            enemyTree.Nodes.Add("4530 Auto-Cloak");
            enemyTree.Nodes.Add("4531 Rush Dance");
            enemyTree.Nodes.Add("4532 Splash Blessing");
            enemyTree.Nodes.Add("4533 BLANK");
            enemyTree.Nodes.Add("4534 BLANK");
            enemyTree.Nodes.Add("4535 BLANK");
            enemyTree.Nodes.Add("4536 BLANK");
            enemyTree.Nodes.Add("4537 BLANK");
            enemyTree.Nodes.Add("4538 BLANK");
            enemyTree.Nodes.Add("4539 BLANK");
            enemyTree.Nodes.Add("4540 BLANK");
            enemyTree.Nodes.Add("4541 BLANK");
            enemyTree.Nodes.Add("4542 BLANK");
            enemyTree.Nodes.Add("4543 BLANK");
            enemyTree.Nodes.Add("4544 BLANK");
            enemyTree.Nodes.Add("4545 BLANK");
            enemyTree.Nodes.Add("4546 BLANK");
            enemyTree.Nodes.Add("4547 BLANK");
            enemyTree.Nodes.Add("4548 BLANK");
            enemyTree.Nodes.Add("4549 BLANK");
            enemyTree.Nodes.Add("4550 BLANK");
            enemyTree.Nodes.Add("4551 BLANK");
            enemyTree.Nodes.Add("4552 BLANK");
            enemyTree.Nodes.Add("4553 BLANK");
            enemyTree.Nodes.Add("4554 BLANK");
            enemyTree.Nodes.Add("4555 BLANK");
            enemyTree.Nodes.Add("4556 BLANK");
            enemyTree.Nodes.Add("4557 BLANK");
            enemyTree.Nodes.Add("4558 BLANK");
            enemyTree.Nodes.Add("4559 End");
            enemyTree.Nodes.Add("4560 Start");
            enemyTree.Nodes.Add("4561 Orgia Mastery");
            enemyTree.Nodes.Add("4562 Spy Arts");
            enemyTree.Nodes.Add("4563 Spy Expertise");
            enemyTree.Nodes.Add("4564 Pose");
            enemyTree.Nodes.Add("4565 Heroic Pose");
            enemyTree.Nodes.Add("4566 Hermit Arts");
            enemyTree.Nodes.Add("4567 Hermit Mastery");
            enemyTree.Nodes.Add("4568 Bloody Vanguard");
            enemyTree.Nodes.Add("4569 Deadly Vanguard");
            enemyTree.Nodes.Add("4570 Empress Arts");
            enemyTree.Nodes.Add("4571 Empress Mastery");
            enemyTree.Nodes.Add("4572 Squire Card");
            enemyTree.Nodes.Add("4573 Knight Card");
            enemyTree.Nodes.Add("4574 Soldier Arts");
            enemyTree.Nodes.Add("4575 Soldier Mastery");
            enemyTree.Nodes.Add("4576 Kung Fu Arts");
            enemyTree.Nodes.Add("4577 Kung Fu Mastery");
            enemyTree.Nodes.Add("4578 Wild Arts");
            enemyTree.Nodes.Add("4579 Wild Arts +");
            enemyTree.Nodes.Add("4580 Brave Soul");
            enemyTree.Nodes.Add("4581 Brave Soul +");
            enemyTree.Nodes.Add("4582 Rebel Spirit");
            enemyTree.Nodes.Add("4583 Uprising");
            enemyTree.Nodes.Add("4584 Circle Master");
            enemyTree.Nodes.Add("4585 Circle Virtuoso");
            enemyTree.Nodes.Add("4586 Brawler Arts");
            enemyTree.Nodes.Add("4587 Brawler Arts +");
            enemyTree.Nodes.Add("4588 Life Support");
            enemyTree.Nodes.Add("4589 Life Support +");
            enemyTree.Nodes.Add("4590 Stance Master");
            enemyTree.Nodes.Add("4591 Stance Virtuoso");
            enemyTree.Nodes.Add("4592 Raging Lion");
            enemyTree.Nodes.Add("4593 Raging Lion +");
            enemyTree.Nodes.Add("4594 Heroic Gemini");
            enemyTree.Nodes.Add("4595 Golden Gemini");
            enemyTree.Nodes.Add("4596 Runic Shield");
            enemyTree.Nodes.Add("4597 Aegis Shield");
            enemyTree.Nodes.Add("4598 Swordbreaker");
            enemyTree.Nodes.Add("4599 BLANK");
            enemyTree.Nodes.Add("4600 BLANK");
            enemyTree.Nodes.Add("4601 First Star");
            enemyTree.Nodes.Add("4602 Binding Hands");
            enemyTree.Nodes.Add("4603 Restoring Touch");
            enemyTree.Nodes.Add("4604 Warrior Title");
            enemyTree.Nodes.Add("4605 Conqueror Title");
            enemyTree.Nodes.Add("4606 Conqueror Arts");
            enemyTree.Nodes.Add("4607 Healing Hand");
            enemyTree.Nodes.Add("4608 Dia Guard");
            enemyTree.Nodes.Add("4609 Diarama Guard");
            enemyTree.Nodes.Add("4610 Colossal Swing");
            enemyTree.Nodes.Add("4611 Whirlwind Swing");
            enemyTree.Nodes.Add("4612 Golden Link");
            enemyTree.Nodes.Add("4613 Perception");
            enemyTree.Nodes.Add("4614 Forked Spear");
            enemyTree.Nodes.Add("4615 Trick Step");
            enemyTree.Nodes.Add("4616 Endure");
            enemyTree.Nodes.Add("4617 Nature's Grace");
            enemyTree.Nodes.Add("4618 Immunity Buffer");
            enemyTree.Nodes.Add("4619 Lemegeton");
            enemyTree.Nodes.Add("4620 Platinum Coin");
            enemyTree.Nodes.Add("4621 Absorb Fire");
            enemyTree.Nodes.Add("4622 Absorb Wind");
            enemyTree.Nodes.Add("4623 Absorb Ice");
            enemyTree.Nodes.Add("4624 Absorb Elec");
            enemyTree.Nodes.Add("4625 BLANK");
            enemyTree.Nodes.Add("4626 Fire Boost");
            enemyTree.Nodes.Add("4627 Ice Boost");
            enemyTree.Nodes.Add("4628 Elec Boost");
            enemyTree.Nodes.Add("4629 Wind Boost");
            enemyTree.Nodes.Add("4630 Fire Amp");
            enemyTree.Nodes.Add("4631 Ice Amp");
            enemyTree.Nodes.Add("4632 Elec Amp");
            enemyTree.Nodes.Add("4633 Wind Amp");
            enemyTree.Nodes.Add("4634 Overheat SP Boost");
            enemyTree.Nodes.Add("4635 Devotion Arts");
            enemyTree.Nodes.Add("4636 Devotion Mastery");
            enemyTree.Nodes.Add("4637 BLANK");
            enemyTree.Nodes.Add("4638 Death's Scythe");
            enemyTree.Nodes.Add("4639 Impure Reach");
            enemyTree.Nodes.Add("4640 BLANK");
            enemyTree.Nodes.Add("4641 Circle Recovery");
            enemyTree.Nodes.Add("4642 King Card");
            enemyTree.Nodes.Add("4643 Inferno Boost");
            enemyTree.Nodes.Add("4644 Tornado Boost");
            enemyTree.Nodes.Add("4645 Powerhouse");
            enemyTree.Nodes.Add("4646 BLANK");
            enemyTree.Nodes.Add("4647 SP Focus");
            enemyTree.Nodes.Add("4648 BLANK");
            enemyTree.Nodes.Add("4649 Target Boost");
            enemyTree.Nodes.Add("4650 Attack Boost I");
            enemyTree.Nodes.Add("4651 Attack Boost II");
            enemyTree.Nodes.Add("4652 Attack Boost III");
            enemyTree.Nodes.Add("4653 Defense Boost I");
            enemyTree.Nodes.Add("4654 Defense Boost II");
            enemyTree.Nodes.Add("4655 Defense Boost III");
            enemyTree.Nodes.Add("4656 Element Boost I");
            enemyTree.Nodes.Add("4657 Element Boost II");
            enemyTree.Nodes.Add("4658 Element Boost III");
            enemyTree.Nodes.Add("4659 Serene Journey");
            enemyTree.Nodes.Add("4660 Serene Quest");
            enemyTree.Nodes.Add("4661 Serene Pilgrimage");
            enemyTree.Nodes.Add("4662 Double Link");
            enemyTree.Nodes.Add("4663 BLANK");
            enemyTree.Nodes.Add("4664 Magic Boost I");
            enemyTree.Nodes.Add("4665 Magic Boost II");
            enemyTree.Nodes.Add("4666 Magic Boost III");
            enemyTree.Nodes.Add("4667 HP Boost");
            enemyTree.Nodes.Add("4668 HP Amp");
            enemyTree.Nodes.Add("4669 SP Boost");
            enemyTree.Nodes.Add("4670 SP Amp");
            enemyTree.Nodes.Add("4671 Agility Boost");
            enemyTree.Nodes.Add("4672 Agility Amp");
            enemyTree.Nodes.Add("4673 Resist Fire");
            enemyTree.Nodes.Add("4674 Resist Ice");
            enemyTree.Nodes.Add("4675 Resist Elec");
            enemyTree.Nodes.Add("4676 Resist Wind");
            enemyTree.Nodes.Add("4677 Resist Light");
            enemyTree.Nodes.Add("4678 Resist Dark");
            enemyTree.Nodes.Add("4679 Resist Cut");
            enemyTree.Nodes.Add("4680 Resist Bash");
            enemyTree.Nodes.Add("4681 Resist Stab");
            enemyTree.Nodes.Add("4682 Null Petrify");
            enemyTree.Nodes.Add("4683 Null Sleep");
            enemyTree.Nodes.Add("4684 Null Panic");
            enemyTree.Nodes.Add("4685 Null Poison");
            enemyTree.Nodes.Add("4686 BLANK");
            enemyTree.Nodes.Add("4687 Null Curse");
            enemyTree.Nodes.Add("4688 Null Paralysis");
            enemyTree.Nodes.Add("4689 BLANK");
            enemyTree.Nodes.Add("4690 Keburi no Sue");
            enemyTree.Nodes.Add("4691 Judgement Sword");
            enemyTree.Nodes.Add("4692 Judgement Sword");
            enemyTree.Nodes.Add("4693 Null M-Bind");
            enemyTree.Nodes.Add("4694 Null S-Bind");
            enemyTree.Nodes.Add("4695 Null A-Bind");
            enemyTree.Nodes.Add("4696 Demon's Cut");
            enemyTree.Nodes.Add("4697 Demon's Bash");
            enemyTree.Nodes.Add("4698 Demon's Stab");
            enemyTree.Nodes.Add("4699 God's Cut");
            enemyTree.Nodes.Add("4700 God's Bash");
            enemyTree.Nodes.Add("4701 God's Stab");
            enemyTree.Nodes.Add("4702 SP Recoil");
            enemyTree.Nodes.Add("4703 SP Redeemer");
            enemyTree.Nodes.Add("4704 Start");
            enemyTree.Nodes.Add("4705 Follow-Up");
            enemyTree.Nodes.Add("4706 Follow-Up");
            enemyTree.Nodes.Add("4707 Follow-Up");
            enemyTree.Nodes.Add("4708 Follow-Up");
            enemyTree.Nodes.Add("4709 Follow-Up");
            enemyTree.Nodes.Add("4710 Follow-Up");
            enemyTree.Nodes.Add("4711 Follow-Up");
            enemyTree.Nodes.Add("4712 Follow-Up");
            enemyTree.Nodes.Add("4713 Follow-Up");
            enemyTree.Nodes.Add("4714 Follow-Up");
            enemyTree.Nodes.Add("4715 Follow-Up");
            enemyTree.Nodes.Add("4716 Follow-Up");
            enemyTree.Nodes.Add("4717 Follow-Up");
            enemyTree.Nodes.Add("4718 Follow-Up");
            enemyTree.Nodes.Add("4719 Follow-Up");
            enemyTree.Nodes.Add("4720 Follow-Up");
            enemyTree.Nodes.Add("4721 Follow-Up");
            enemyTree.Nodes.Add("4722 Follow-Up");
            enemyTree.Nodes.Add("4723 Follow-Up");
            enemyTree.Nodes.Add("4724 Follow-Up");
            enemyTree.Nodes.Add("4725 BLANK");
            enemyTree.Nodes.Add("4726 BLANK");
            enemyTree.Nodes.Add("4727 BLANK");
            enemyTree.Nodes.Add("4728 BLANK");
            enemyTree.Nodes.Add("4729 BLANK");
            enemyTree.Nodes.Add("4730 BLANK");
            enemyTree.Nodes.Add("4731 BLANK");
            enemyTree.Nodes.Add("4732 BLANK");
            enemyTree.Nodes.Add("4733 BLANK");
            enemyTree.Nodes.Add("4734 BLANK");
            enemyTree.Nodes.Add("4735 End");
            enemyTree.Nodes.Add("4736 Start");
            enemyTree.Nodes.Add("4737 Medicine");
            enemyTree.Nodes.Add("4738 Oinment");
            enemyTree.Nodes.Add("4739 Antibiotic Gel");
            enemyTree.Nodes.Add("4740 Bead");
            enemyTree.Nodes.Add("4741 Soul Drop");
            enemyTree.Nodes.Add("4742 Snuff Soul");
            enemyTree.Nodes.Add("4743 Chewing Soul");
            enemyTree.Nodes.Add("4744 Soul Food");
            enemyTree.Nodes.Add("4745 Soma Droplet");
            enemyTree.Nodes.Add("4746 Soma Tear");
            enemyTree.Nodes.Add("4747 Revival Bead");
            enemyTree.Nodes.Add("4748 Balm of Life");
            enemyTree.Nodes.Add("4749 Emergency Kit");
            enemyTree.Nodes.Add("4750 Medical Kit");
            enemyTree.Nodes.Add("4751 Mutudi Gem");
            enemyTree.Nodes.Add("4752 Patra Gem");
            enemyTree.Nodes.Add("4753 Purifying Water");
            enemyTree.Nodes.Add("4754 Purifying Salt");
            enemyTree.Nodes.Add("4755 Bravant");
            enemyTree.Nodes.Add("4756 Stonard");
            enemyTree.Nodes.Add("4757 Cut Mist");
            enemyTree.Nodes.Add("4758 Bash Mist");
            enemyTree.Nodes.Add("4759 Stab Mist");
            enemyTree.Nodes.Add("4760 Fire Mist");
            enemyTree.Nodes.Add("4761 Ice Mist");
            enemyTree.Nodes.Add("4762 Elec Mist");
            enemyTree.Nodes.Add("4763 Wind Mist");
            enemyTree.Nodes.Add("4764 Blaze Oil");
            enemyTree.Nodes.Add("4765 Freeze Oil");
            enemyTree.Nodes.Add("4766 Shock Oil");
            enemyTree.Nodes.Add("4767 Cyclone Oil");
            enemyTree.Nodes.Add("4768 San-zun Tama");
            enemyTree.Nodes.Add("4769 Scorching Magatama");
            enemyTree.Nodes.Add("4770 Dry Ice");
            enemyTree.Nodes.Add("4771 Zero Magatama");
            enemyTree.Nodes.Add("4772 Tesla Coil");
            enemyTree.Nodes.Add("4773 Bolt Magatama");
            enemyTree.Nodes.Add("4774 Yashichi");
            enemyTree.Nodes.Add("4775 Storm Magatama");
            enemyTree.Nodes.Add("4776 Segaki Rice");
            enemyTree.Nodes.Add("4777 Curse Paper");
            enemyTree.Nodes.Add("4778 Poison Gas");
            enemyTree.Nodes.Add("4779 Paralysis Gas");
            enemyTree.Nodes.Add("4780 Vanish Ball");
            enemyTree.Nodes.Add("4781 Sleep Gas");
            enemyTree.Nodes.Add("4782 Curse Gas");
            enemyTree.Nodes.Add("4783 Panic Gas");
            enemyTree.Nodes.Add("4784 Analysis Scope");
            enemyTree.Nodes.Add("4785 Homunculus");
            enemyTree.Nodes.Add("4786 Disperse Amulet");
            enemyTree.Nodes.Add("4787 Summon Charm");
            enemyTree.Nodes.Add("4788 Goho-M");
            enemyTree.Nodes.Add("4789 Goba-K");
            enemyTree.Nodes.Add("4790 Winged Sandals");
            enemyTree.Nodes.Add("4791 Sight Beacon");
            enemyTree.Nodes.Add("4792 Soma");
            enemyTree.Nodes.Add("4793 Soma Jelly");
            enemyTree.Nodes.Add("4794 Bead Chain");
            enemyTree.Nodes.Add("4795 Dawn Charm");
            enemyTree.Nodes.Add("4796 Repulse Bell");
            enemyTree.Nodes.Add("4797 Attract Pipe");
            enemyTree.Nodes.Add("4798 Heal Stone");
            enemyTree.Nodes.Add("4799 End");
            enemyTree.Nodes.Add("4800 Ailment Boost");
            enemyTree.Nodes.Add("4801 Ailment Surge");
            enemyTree.Nodes.Add("4802 Raging Fists");
            enemyTree.Nodes.Add("4803 Furious Fists");
            enemyTree.Nodes.Add("4804 Punisher");
            enemyTree.Nodes.Add("4805 BLANK");
            enemyTree.Nodes.Add("4806 BLANK");
            enemyTree.Nodes.Add("4807 BLANK");
            enemyTree.Nodes.Add("4808 BLANK");
            enemyTree.Nodes.Add("4809 BLANK");
            enemyTree.Nodes.Add("4810 BLANK");
            enemyTree.Nodes.Add("4811 Return from Yomi");
            enemyTree.Nodes.Add("4812 Triple Link");
            enemyTree.Nodes.Add("4813 Quadruple Link");
            enemyTree.Nodes.Add("4814 Infinite Link");
            enemyTree.Nodes.Add("4815 Magic Aura");
            enemyTree.Nodes.Add("4816 Skill Boost");
            enemyTree.Nodes.Add("4817 Heroic Spring");
            enemyTree.Nodes.Add("4818 Circle Aura");
            enemyTree.Nodes.Add("4819 Healing Surge");
            enemyTree.Nodes.Add("4820 Stun Recovery");
            enemyTree.Nodes.Add("4821 Overheat");
            enemyTree.Nodes.Add("4822 Overheat End");
            enemyTree.Nodes.Add("4823 RESERVE");
            enemyTree.Nodes.Add("4824 RESERVE");
            enemyTree.Nodes.Add("4825 RESERVE");
            enemyTree.Nodes.Add("4826 RESERVE");
            enemyTree.Nodes.Add("4827 RESERVE");
            enemyTree.Nodes.Add("4828 RESERVE");
            enemyTree.Nodes.Add("4829 RESERVE");
            enemyTree.Nodes.Add("4830 RESERVE");
            enemyTree.Nodes.Add("4831 RESERVE");
            enemyTree.Nodes.Add("4832 RESERVE");
            enemyTree.Nodes.Add("4833 RESERVE");
            enemyTree.Nodes.Add("4834 RESERVE");
            enemyTree.Nodes.Add("4835 RESERVE");
            enemyTree.Nodes.Add("4836 RESERVE");
            enemyTree.Nodes.Add("4837 RESERVE");
            enemyTree.Nodes.Add("4838 RESERVE");
            enemyTree.Nodes.Add("4839 RESERVE");
            enemyTree.Nodes.Add("4840 RESERVE");
            enemyTree.Nodes.Add("4841 RESERVE");
            enemyTree.Nodes.Add("4842 RESERVE");
            enemyTree.Nodes.Add("4843 RESERVE");
            enemyTree.Nodes.Add("4844 RESERVE");
            enemyTree.Nodes.Add("4845 RESERVE");
            enemyTree.Nodes.Add("4846 RESERVE");
            enemyTree.Nodes.Add("4847 RESERVE");
            enemyTree.Nodes.Add("4848 RESERVE");
            enemyTree.Nodes.Add("4849 RESERVE");
            enemyTree.Nodes.Add("4850 RESERVE");
            enemyTree.Nodes.Add("4851 RESERVE");
            enemyTree.Nodes.Add("4852 RESERVE");
            enemyTree.Nodes.Add("4853 RESERVE");
            enemyTree.Nodes.Add("4854 RESERVE");
            enemyTree.Nodes.Add("4855 RESERVE");
            enemyTree.Nodes.Add("4856 RESERVE");
            enemyTree.Nodes.Add("4857 RESERVE");
            enemyTree.Nodes.Add("4858 RESERVE");
            enemyTree.Nodes.Add("4859 RESERVE");
            enemyTree.Nodes.Add("4860 RESERVE");
            enemyTree.Nodes.Add("4861 RESERVE");
            enemyTree.Nodes.Add("4862 RESERVE");
            enemyTree.Nodes.Add("4863 REVERSE/BLANK");
            enemyTree.Nodes.Add("4864 BLANK");
            enemyTree.Nodes.Add("4865 Agi");
            enemyTree.Nodes.Add("4866 Agilao");
            enemyTree.Nodes.Add("4867 Agidyne");
            enemyTree.Nodes.Add("4868 Maragi");
            enemyTree.Nodes.Add("4869 Maragion");
            enemyTree.Nodes.Add("4870 Maragidyne");
            enemyTree.Nodes.Add("4871 Fire Dance");
            enemyTree.Nodes.Add("4872 BLANK");
            enemyTree.Nodes.Add("4873 BLANK");
            enemyTree.Nodes.Add("4874 BLANK");
            enemyTree.Nodes.Add("4875 Garu");
            enemyTree.Nodes.Add("4876 Garula");
            enemyTree.Nodes.Add("4877 Garudyne");
            enemyTree.Nodes.Add("4878 Magaru");
            enemyTree.Nodes.Add("4879 Magarula");
            enemyTree.Nodes.Add("4880 Magarudyne");
            enemyTree.Nodes.Add("4881 Wind Dance");
            enemyTree.Nodes.Add("4882 BLANK");
            enemyTree.Nodes.Add("4883 BLANK");
            enemyTree.Nodes.Add("4884 BLANK");
            enemyTree.Nodes.Add("4885 Bufu");
            enemyTree.Nodes.Add("4886 Bufula");
            enemyTree.Nodes.Add("4887 Bufudyne");
            enemyTree.Nodes.Add("4888 Mabufu");
            enemyTree.Nodes.Add("4889 Mabufula");
            enemyTree.Nodes.Add("4890 Mabufudyne");
            enemyTree.Nodes.Add("4891 Absolute Zero");
            enemyTree.Nodes.Add("4892 Ice Dance");
            enemyTree.Nodes.Add("4893 BLANK");
            enemyTree.Nodes.Add("4894 BLANK");
            enemyTree.Nodes.Add("4895 BLANK");
            enemyTree.Nodes.Add("4896 Zio");
            enemyTree.Nodes.Add("4897 Zionga");
            enemyTree.Nodes.Add("4898 Ziodyne");
            enemyTree.Nodes.Add("4899 Mazio");
            enemyTree.Nodes.Add("4900 Mazionga");
            enemyTree.Nodes.Add("4901 Maziodyne");
            enemyTree.Nodes.Add("4902 Keraunos");
            enemyTree.Nodes.Add("4903 Elec Dance");
            enemyTree.Nodes.Add("4904 BLANK");
            enemyTree.Nodes.Add("4905 BLANK");
            enemyTree.Nodes.Add("4906 BLANK");
            enemyTree.Nodes.Add("4907 Megido");
            enemyTree.Nodes.Add("4908 Megidola");
            enemyTree.Nodes.Add("4909 Megidolaon");
            enemyTree.Nodes.Add("4910 BLANK");
            enemyTree.Nodes.Add("4911 BLANK");
            enemyTree.Nodes.Add("4912 BLANK");
            enemyTree.Nodes.Add("4913 Hama");
            enemyTree.Nodes.Add("4914 Hamaon");
            enemyTree.Nodes.Add("4915 Mahama");
            enemyTree.Nodes.Add("4916 Mahamaon");
            enemyTree.Nodes.Add("4917 BLANK");
            enemyTree.Nodes.Add("4918 BLANK");
            enemyTree.Nodes.Add("4919 BLANK");
            enemyTree.Nodes.Add("4920 Mudo");
            enemyTree.Nodes.Add("4921 Mudoon");
            enemyTree.Nodes.Add("4922 Mamudo");
            enemyTree.Nodes.Add("4923 Mamudoon");
            enemyTree.Nodes.Add("4924 BLANK");
            enemyTree.Nodes.Add("4925 BLANK");
            enemyTree.Nodes.Add("4926 BLANK");
            enemyTree.Nodes.Add("4927 Poisma");
            enemyTree.Nodes.Add("4928 Poison Breath");
            enemyTree.Nodes.Add("4929 Stona");
            enemyTree.Nodes.Add("4930 Stone Mist");
            enemyTree.Nodes.Add("4931 Dormina");
            enemyTree.Nodes.Add("4932 Lullaby Song");
            enemyTree.Nodes.Add("4933 Pulinpa");
            enemyTree.Nodes.Add("4934 Tentarafoo");
            enemyTree.Nodes.Add("4935 BLANK");
            enemyTree.Nodes.Add("4936 BLANK");
            enemyTree.Nodes.Add("4937 Evil Touch");
            enemyTree.Nodes.Add("4938 Evil Smile");
            enemyTree.Nodes.Add("4939 Shibaboo");
            enemyTree.Nodes.Add("4940 Binding Cry");
            enemyTree.Nodes.Add("4941 Makajam");
            enemyTree.Nodes.Add("4942 Silent Song");
            enemyTree.Nodes.Add("4943 Disarm");
            enemyTree.Nodes.Add("4944 Muscle Down");
            enemyTree.Nodes.Add("4945 Scarecrow");
            enemyTree.Nodes.Add("4946 Spiderweb");
            enemyTree.Nodes.Add("4947 Self-Destruct");
            enemyTree.Nodes.Add("4948 BLANK");
            enemyTree.Nodes.Add("4949 BLANK");
            enemyTree.Nodes.Add("4950 BLANK");
            enemyTree.Nodes.Add("4951 BLANK");
            enemyTree.Nodes.Add("4952 BLANK");
            enemyTree.Nodes.Add("4953 BLANK");
            enemyTree.Nodes.Add("4954 BLANK");
            enemyTree.Nodes.Add("4955 BLANK");
            enemyTree.Nodes.Add("4956 BLANK");
            enemyTree.Nodes.Add("4957 BLANK");
            enemyTree.Nodes.Add("4958 BLANK");
            enemyTree.Nodes.Add("4959 BLANK");
            enemyTree.Nodes.Add("4960 BLANK");
            enemyTree.Nodes.Add("4961 BLANK");
            enemyTree.Nodes.Add("4962 BLANK");
            enemyTree.Nodes.Add("4963 BLANK");
            enemyTree.Nodes.Add("4964 BLANK");
            enemyTree.Nodes.Add("4965 BLANK");
            enemyTree.Nodes.Add("4966 BLANK");
            enemyTree.Nodes.Add("4967 BLANK");
            enemyTree.Nodes.Add("4968 BLANK");
            enemyTree.Nodes.Add("4969 BLANK");
            enemyTree.Nodes.Add("4970 BLANK");
            enemyTree.Nodes.Add("4971 BLANK");
            enemyTree.Nodes.Add("4972 BLANK");
            enemyTree.Nodes.Add("4973 BLANK");
            enemyTree.Nodes.Add("4974 BLANK");
            enemyTree.Nodes.Add("4975 BLANK");
            enemyTree.Nodes.Add("4976 BLANK");
            enemyTree.Nodes.Add("4977 BLANK");
            enemyTree.Nodes.Add("4978 BLANK");
            enemyTree.Nodes.Add("4979 BLANK");
            enemyTree.Nodes.Add("4980 BLANK");
            enemyTree.Nodes.Add("4981 BLANK");
            enemyTree.Nodes.Add("4982 BLANK");
            enemyTree.Nodes.Add("4983 BLANK");
            enemyTree.Nodes.Add("4984 BLANK");
            enemyTree.Nodes.Add("4985 BLANK");
            enemyTree.Nodes.Add("4986 BLANK");
            enemyTree.Nodes.Add("4987 BLANK");
            enemyTree.Nodes.Add("4988 BLANK");
            enemyTree.Nodes.Add("4989 BLANK");
            enemyTree.Nodes.Add("4990 BLANK");
            enemyTree.Nodes.Add("4991 BLANK");
            enemyTree.Nodes.Add("4992 BLANK");
            enemyTree.Nodes.Add("4993 Fang Smash");
            enemyTree.Nodes.Add("4994 Kidney Smash");
            enemyTree.Nodes.Add("4995 Cleave");
            enemyTree.Nodes.Add("4996 Twin Slash");
            enemyTree.Nodes.Add("4997 Lunge");
            enemyTree.Nodes.Add("4998 Twin Shot");
            enemyTree.Nodes.Add("4999 Mighty Swing");
            enemyTree.Nodes.Add("5000 Hard Slash");
            enemyTree.Nodes.Add("5001 Charge Shot");
            enemyTree.Nodes.Add("5002 Stab Shower");
            enemyTree.Nodes.Add("5003 Frost Edge");
            enemyTree.Nodes.Add("5004 Guillotine");
            enemyTree.Nodes.Add("5005 Tempest Slash");
            enemyTree.Nodes.Add("5006 Lightning Smash");
            enemyTree.Nodes.Add("5007 Drain Touch");
            enemyTree.Nodes.Add("5008 Gigantic Fist");
            enemyTree.Nodes.Add("5009 Single Shot");
            enemyTree.Nodes.Add("5010 Thorn Shackles");
            enemyTree.Nodes.Add("5011 Thorn Cuffs");
            enemyTree.Nodes.Add("5012 Thorn Chains");
            enemyTree.Nodes.Add("5013 Assault Shot");
            enemyTree.Nodes.Add("5014 Primal Force");
            enemyTree.Nodes.Add("5015 Heavy Shot");
            enemyTree.Nodes.Add("5016 Broadshot");
            enemyTree.Nodes.Add("5017 Myriad Arrows");
            enemyTree.Nodes.Add("5018 Megaton Press");
            enemyTree.Nodes.Add("5019 Brain Shake");
            enemyTree.Nodes.Add("5020 Stardrop");
            enemyTree.Nodes.Add("5021 Buchikamashi");
            enemyTree.Nodes.Add("5022 Spin Slash");
            enemyTree.Nodes.Add("5023 Blade of Fury");
            enemyTree.Nodes.Add("5024 Tousatsujin");
            enemyTree.Nodes.Add("5025 Vorpal Blade");
            enemyTree.Nodes.Add("5026 Crazed Slash");
            enemyTree.Nodes.Add("5027 Skull Cracker");
            enemyTree.Nodes.Add("5028 Scorching Blast");
            enemyTree.Nodes.Add("5029 Heat Wave");
            enemyTree.Nodes.Add("5030 Megaton Slam");
            enemyTree.Nodes.Add("5031 Megaton Slam");
            enemyTree.Nodes.Add("5032 Blinding Slice");
            enemyTree.Nodes.Add("5033 Toxic Slice");
            enemyTree.Nodes.Add("5034 Dream Slice");
            enemyTree.Nodes.Add("5035 Stunning Slice");
            enemyTree.Nodes.Add("5036 Bane Slice");
            enemyTree.Nodes.Add("5037 Mow Down");
            enemyTree.Nodes.Add("5038 Deathbound");
            enemyTree.Nodes.Add("5039 Torrent Shot");
            enemyTree.Nodes.Add("5040 Rampage");
            enemyTree.Nodes.Add("5041 BLANK");
            enemyTree.Nodes.Add("5042 BLANK");
            enemyTree.Nodes.Add("5043 BLANK");
            enemyTree.Nodes.Add("5044 BLANK");
            enemyTree.Nodes.Add("5045 BLANK");
            enemyTree.Nodes.Add("5046 BLANK");
            enemyTree.Nodes.Add("5047 BLANK");
            enemyTree.Nodes.Add("5048 BLANK");
            enemyTree.Nodes.Add("5049 BLANK");
            enemyTree.Nodes.Add("5050 BLANK");
            enemyTree.Nodes.Add("5051 BLANK");
            enemyTree.Nodes.Add("5052 BLANK");
            enemyTree.Nodes.Add("5053 BLANK");
            enemyTree.Nodes.Add("5054 BLANK");
            enemyTree.Nodes.Add("5055 BLANK");
            enemyTree.Nodes.Add("5056 BLANK");
            enemyTree.Nodes.Add("5057 BLANK");
            enemyTree.Nodes.Add("5058 BLANK");
            enemyTree.Nodes.Add("5059 BLANK");
            enemyTree.Nodes.Add("5060 BLANK");
            enemyTree.Nodes.Add("5061 BLANK");
            enemyTree.Nodes.Add("5062 BLANK");
            enemyTree.Nodes.Add("5063 BLANK");
            enemyTree.Nodes.Add("5064 BLANK");
            enemyTree.Nodes.Add("5065 BLANK");
            enemyTree.Nodes.Add("5066 BLANK");
            enemyTree.Nodes.Add("5067 BLANK");
            enemyTree.Nodes.Add("5068 BLANK");
            enemyTree.Nodes.Add("5069 BLANK");
            enemyTree.Nodes.Add("5070 BLANK");
            enemyTree.Nodes.Add("5071 BLANK");
            enemyTree.Nodes.Add("5072 BLANK");
            enemyTree.Nodes.Add("5073 Dia");
            enemyTree.Nodes.Add("5074 Diarama");
            enemyTree.Nodes.Add("5075 Diarahan");
            enemyTree.Nodes.Add("5076 BLANK");
            enemyTree.Nodes.Add("5077 BLANK");
            enemyTree.Nodes.Add("5078 Media");
            enemyTree.Nodes.Add("5079 Mediarama");
            enemyTree.Nodes.Add("5080 Mediarahan");
            enemyTree.Nodes.Add("5081 BLANK");
            enemyTree.Nodes.Add("5082 Samarecarm");
            enemyTree.Nodes.Add("5083 BLANK");
            enemyTree.Nodes.Add("5084 BLANK");
            enemyTree.Nodes.Add("5085 Patra");
            enemyTree.Nodes.Add("5086 BLANK");
            enemyTree.Nodes.Add("5087 BLANK");
            enemyTree.Nodes.Add("5088 Mutudi");
            enemyTree.Nodes.Add("5089 BLANK");
            enemyTree.Nodes.Add("5090 BLANK");
            enemyTree.Nodes.Add("5091 BLANK");
            enemyTree.Nodes.Add("5092 BLANK");
            enemyTree.Nodes.Add("5093 Bestial Roar");
            enemyTree.Nodes.Add("5094 BLANK");
            enemyTree.Nodes.Add("5095 BLANK");
            enemyTree.Nodes.Add("5096 Rampart");
            enemyTree.Nodes.Add("5097 Safeguard");
            enemyTree.Nodes.Add("5098 BLANK");
            enemyTree.Nodes.Add("5099 Life Wall");
            enemyTree.Nodes.Add("5100 BLANK");
            enemyTree.Nodes.Add("5101 BLANK");
            enemyTree.Nodes.Add("5102 BLANK");
            enemyTree.Nodes.Add("5103 BLANK");
            enemyTree.Nodes.Add("5104 BLANK");
            enemyTree.Nodes.Add("5105 BLANK");
            enemyTree.Nodes.Add("5106 Matarukaja");
            enemyTree.Nodes.Add("5107 Marakukaja");
            enemyTree.Nodes.Add("5108 Masukukaja");
            enemyTree.Nodes.Add("5109 Power Charge");
            enemyTree.Nodes.Add("5110 Mind Charge");
            enemyTree.Nodes.Add("5111 Fire Corrosion");
            enemyTree.Nodes.Add("5112 Ice Corrosion");
            enemyTree.Nodes.Add("5113 Elec Corrosion");
            enemyTree.Nodes.Add("5114 Wind Corrosion");
            enemyTree.Nodes.Add("5115 BLANK");
            enemyTree.Nodes.Add("5116 BLANK");
            enemyTree.Nodes.Add("5117 Matarunda");
            enemyTree.Nodes.Add("5118 Marakunda");
            enemyTree.Nodes.Add("5119 Masukunda");
            enemyTree.Nodes.Add("5120 BLANK");
            enemyTree.Nodes.Add("5121 Dekaja");
            enemyTree.Nodes.Add("5122 Dekunda");
            enemyTree.Nodes.Add("5123 BLANK");
            enemyTree.Nodes.Add("5124 Escape");
            enemyTree.Nodes.Add("5125 ");
            enemyTree.Nodes.Add("5126 ");
            enemyTree.Nodes.Add("5127 Tarukaja");
            enemyTree.Nodes.Add("5128 Rakukaja");
            enemyTree.Nodes.Add("5129 Sukukaja");
            enemyTree.Nodes.Add("5130 Tarunda");
            enemyTree.Nodes.Add("5131 Rakunda");
            enemyTree.Nodes.Add("5132 Sukunda");
            enemyTree.Nodes.Add("5133 BLANK");
            enemyTree.Nodes.Add("5134 BLANK");
            enemyTree.Nodes.Add("5135 BLANK");
            enemyTree.Nodes.Add("5136 BLANK");
            enemyTree.Nodes.Add("5137 BLANK");
            enemyTree.Nodes.Add("5138 BLANK");
            enemyTree.Nodes.Add("5139 BLANK");
            enemyTree.Nodes.Add("5140 BLANK");
            enemyTree.Nodes.Add("5141 BLANK");
            enemyTree.Nodes.Add("5142 BLANK");
            enemyTree.Nodes.Add("5143 BLANK");
            enemyTree.Nodes.Add("5144 BLANK");
            enemyTree.Nodes.Add("5145 BLANK");
            enemyTree.Nodes.Add("5146 BLANK");
            enemyTree.Nodes.Add("5147 BLANK");
            enemyTree.Nodes.Add("5148 BLANK");
            enemyTree.Nodes.Add("5149 BLANK");
            enemyTree.Nodes.Add("5150 BLANK");
            enemyTree.Nodes.Add("5151 BLANK");
            enemyTree.Nodes.Add("5152 BLANK");
            enemyTree.Nodes.Add("5153 BLANK");
            enemyTree.Nodes.Add("5154 BLANK");
            enemyTree.Nodes.Add("5155 BLANK");
            enemyTree.Nodes.Add("5156 BLANK");
            enemyTree.Nodes.Add("5157 BLANK");
            enemyTree.Nodes.Add("5158 BLANK");
            enemyTree.Nodes.Add("5159 BLANK");
            enemyTree.Nodes.Add("5160 BLANK");
            enemyTree.Nodes.Add("5161 BLANK");
            enemyTree.Nodes.Add("5162 BLANK");
            enemyTree.Nodes.Add("5163 BLANK");
            enemyTree.Nodes.Add("5164 BLANK");
            enemyTree.Nodes.Add("5165 BLANK");
            enemyTree.Nodes.Add("5166 BLANK");
            enemyTree.Nodes.Add("5167 BLANK");
            enemyTree.Nodes.Add("5168 BLANK");
            enemyTree.Nodes.Add("5169 Fire Boost");
            enemyTree.Nodes.Add("5170 Ice Boost");
            enemyTree.Nodes.Add("5171 Elec Boost");
            enemyTree.Nodes.Add("5172 Wind Boost");
            enemyTree.Nodes.Add("5173 Trick Step");
            enemyTree.Nodes.Add("5174 Recovery Up");
            enemyTree.Nodes.Add("5175 Phys Boost");
            enemyTree.Nodes.Add("5176 Phys Boost II");
            enemyTree.Nodes.Add("5177 Magic Boost");
            enemyTree.Nodes.Add("5178 Magic Boost II");
            enemyTree.Nodes.Add("5179 Wide Effect");
            enemyTree.Nodes.Add("5180 Wide Effect II");
            enemyTree.Nodes.Add("5181 Wide Effect III");
            enemyTree.Nodes.Add("5182 Double Action");
            enemyTree.Nodes.Add("5183 Double Action II");
            enemyTree.Nodes.Add("5184 Double Action III");
            enemyTree.Nodes.Add("5185 BLANK");
            enemyTree.Nodes.Add("5186 BLANK");
            enemyTree.Nodes.Add("5187 BLANK");
            enemyTree.Nodes.Add("5188 BLANK");
            enemyTree.Nodes.Add("5189 BLANK");
            enemyTree.Nodes.Add("5190 BLANK");
            enemyTree.Nodes.Add("5191 BLANK");
            enemyTree.Nodes.Add("5192 BLANK");
            enemyTree.Nodes.Add("5193 BLANK");
            enemyTree.Nodes.Add("5194 BLANK");
            enemyTree.Nodes.Add("5195 BLANK");
            enemyTree.Nodes.Add("5196 BLANK");
            enemyTree.Nodes.Add("5197 BLANK");
            enemyTree.Nodes.Add("5198 BLANK");
            enemyTree.Nodes.Add("5199 BLANK");
            enemyTree.Nodes.Add("5200 BLANK");
            enemyTree.Nodes.Add("5201 BLANK");
            enemyTree.Nodes.Add("5202 BLANK");
            enemyTree.Nodes.Add("5203 BLANK");
            enemyTree.Nodes.Add("5204 BLANK");
            enemyTree.Nodes.Add("5205 BLANK");
            enemyTree.Nodes.Add("5206 BLANK");
            enemyTree.Nodes.Add("5207 BLANK");
            enemyTree.Nodes.Add("5208 BLANK");
            enemyTree.Nodes.Add("5209 BLANK");
            enemyTree.Nodes.Add("5210 BLANK");
            enemyTree.Nodes.Add("5211 BLANK");
            enemyTree.Nodes.Add("5212 BLANK");
            enemyTree.Nodes.Add("5213 BLANK");
            enemyTree.Nodes.Add("5214 BLANK");
            enemyTree.Nodes.Add("5215 BLANK");
            enemyTree.Nodes.Add("5216 BLANK");
            enemyTree.Nodes.Add("5217 BLANK");
            enemyTree.Nodes.Add("5218 BLANK");
            enemyTree.Nodes.Add("5219 BLANK");
            enemyTree.Nodes.Add("5220 BLANK");
            enemyTree.Nodes.Add("5221 BLANK");
            enemyTree.Nodes.Add("5222 BLANK");
            enemyTree.Nodes.Add("5223 BLANK");
            enemyTree.Nodes.Add("5224 BLANK");
            enemyTree.Nodes.Add("5225 BLANK");
            enemyTree.Nodes.Add("5226 BLANK");
            enemyTree.Nodes.Add("5227 BLANK");
            enemyTree.Nodes.Add("5228 BLANK");
            enemyTree.Nodes.Add("5229 BLANK");
            enemyTree.Nodes.Add("5230 BLANK");
            enemyTree.Nodes.Add("5231 BLANK");
            enemyTree.Nodes.Add("5232 BLANK");
            enemyTree.Nodes.Add("5233 BLANK");
            enemyTree.Nodes.Add("5234 BLANK");
            enemyTree.Nodes.Add("5235 BLANK");
            enemyTree.Nodes.Add("5236 BLANK");
            enemyTree.Nodes.Add("5237 BLANK");
            enemyTree.Nodes.Add("5238 BLANK");
            enemyTree.Nodes.Add("5239 BLANK");
            enemyTree.Nodes.Add("5240 BLANK");
            enemyTree.Nodes.Add("5241 BLANK");
            enemyTree.Nodes.Add("5242 BLANK");
            enemyTree.Nodes.Add("5243 BLANK");
            enemyTree.Nodes.Add("5244 BLANK");
            enemyTree.Nodes.Add("5245 BLANK");
            enemyTree.Nodes.Add("5246 BLANK");
            enemyTree.Nodes.Add("5247 BLANK");
            enemyTree.Nodes.Add("5248 BLANK");
            enemyTree.Nodes.Add("5249 BLANK");
            enemyTree.Nodes.Add("5250 BLANK");
            enemyTree.Nodes.Add("5251 BLANK");
            enemyTree.Nodes.Add("5252 BLANK");
            enemyTree.Nodes.Add("5253 BLANK");
            enemyTree.Nodes.Add("5254 BLANK");
            enemyTree.Nodes.Add("5255 BLANK");
            enemyTree.Nodes.Add("5256 BLANK");
            enemyTree.Nodes.Add("5257 BLANK");
            enemyTree.Nodes.Add("5258 BLANK");
            enemyTree.Nodes.Add("5259 BLANK");
            enemyTree.Nodes.Add("5260 BLANK");
            enemyTree.Nodes.Add("5261 BLANK");
            enemyTree.Nodes.Add("5262 BLANK");
            enemyTree.Nodes.Add("5263 BLANK");
            enemyTree.Nodes.Add("5264 BLANK");
            enemyTree.Nodes.Add("5265 BLANK");
            enemyTree.Nodes.Add("5266 BLANK");
            enemyTree.Nodes.Add("5267 BLANK");
            enemyTree.Nodes.Add("5268 BLANK");
            enemyTree.Nodes.Add("5269 BLANK");
            enemyTree.Nodes.Add("5270 BLANK");
            enemyTree.Nodes.Add("5271 BLANK");
            enemyTree.Nodes.Add("5272 BLANK");
            enemyTree.Nodes.Add("5273 BLANK");
            enemyTree.Nodes.Add("5274 BLANK");
            enemyTree.Nodes.Add("5275 BLANK");
            enemyTree.Nodes.Add("5276 BLANK");
            enemyTree.Nodes.Add("5277 BLANK");
            enemyTree.Nodes.Add("5278 BLANK");
            enemyTree.Nodes.Add("5279 BLANK");
            enemyTree.Nodes.Add("5280 BLANK");
            enemyTree.Nodes.Add("5281 Soldier Summon");
            enemyTree.Nodes.Add("5282 Reinforcements");
            enemyTree.Nodes.Add("5283 BLANK");
            enemyTree.Nodes.Add("5284 Holy Wrath");
            enemyTree.Nodes.Add("5285 Vow");
            enemyTree.Nodes.Add("5286 BLANK");
            enemyTree.Nodes.Add("5287 BLANK");
            enemyTree.Nodes.Add("5288 BLANK");
            enemyTree.Nodes.Add("5289 BLANK");
            enemyTree.Nodes.Add("5290 BLANK");
            enemyTree.Nodes.Add("5291 BLANK");
            enemyTree.Nodes.Add("5292 BLANK");
            enemyTree.Nodes.Add("5293 BLANK");
            enemyTree.Nodes.Add("5294 BLANK");
            enemyTree.Nodes.Add("5295 Drastic Measure");
            enemyTree.Nodes.Add("5296 Endure");
            enemyTree.Nodes.Add("5297 Rabbit's Foot");
            enemyTree.Nodes.Add("5298 Deafening Roar");
            enemyTree.Nodes.Add("5299 BLANK");
            enemyTree.Nodes.Add("5300 Gears of Time");
            enemyTree.Nodes.Add("5301 Time Warp");
            enemyTree.Nodes.Add("5302 Death Sentence");
            enemyTree.Nodes.Add("5303 Time Reversal");
            enemyTree.Nodes.Add("5304 Time Stop");
            enemyTree.Nodes.Add("5305 BLANK");
            enemyTree.Nodes.Add("5306 ");
            enemyTree.Nodes.Add("5307 BLANK");
            enemyTree.Nodes.Add("5308 ");
            enemyTree.Nodes.Add("5309 BLANK");
            enemyTree.Nodes.Add("5310 BLANK");
            enemyTree.Nodes.Add("5311 BLANK");
            enemyTree.Nodes.Add("5312 BLANK");
            enemyTree.Nodes.Add("5313 BLANK");
            enemyTree.Nodes.Add("5314 BLANK");
            enemyTree.Nodes.Add("5315 BLANK");
            enemyTree.Nodes.Add("5316 BLANK");
            enemyTree.Nodes.Add("5317 BLANK");
            enemyTree.Nodes.Add("5318 BLANK");
            enemyTree.Nodes.Add("5319 BLANK");
            enemyTree.Nodes.Add("5320 BLANK");
            enemyTree.Nodes.Add("5321 BLANK");
            enemyTree.Nodes.Add("5322 All-Out Attack");
            enemyTree.Nodes.Add("5323 Megidolaon");
            enemyTree.Nodes.Add("5324 BLANK");
            enemyTree.Nodes.Add("5325 BLANK");
            enemyTree.Nodes.Add("5326 BLANK");
            enemyTree.Nodes.Add("5327 BLANK");
            enemyTree.Nodes.Add("5328 BLANK");
            enemyTree.Nodes.Add("5329 BLANK");
            enemyTree.Nodes.Add("5330 BLANK");
            enemyTree.Nodes.Add("5331 BLANK");
            enemyTree.Nodes.Add("5332 BLANK");
            enemyTree.Nodes.Add("5333 BLANK");
            enemyTree.Nodes.Add("5334 BLANK");
            enemyTree.Nodes.Add("5335 BLANK");
            enemyTree.Nodes.Add("5336 BLANK");
            enemyTree.Nodes.Add("5337 BLANK");
            enemyTree.Nodes.Add("5338 BLANK");
            enemyTree.Nodes.Add("5339 BLANK");
            enemyTree.Nodes.Add("5340 BLANK");
            enemyTree.Nodes.Add("5341 BLANK");
            enemyTree.Nodes.Add("5342 BLANK");
            enemyTree.Nodes.Add("5343 BLANK");
            enemyTree.Nodes.Add("5344 BLANK");
            enemyTree.Nodes.Add("5345 BLANK");
            enemyTree.Nodes.Add("5346 BLANK");
            enemyTree.Nodes.Add("5347 BLANK");
            enemyTree.Nodes.Add("5348 BLANK");
            enemyTree.Nodes.Add("5349 BLANK");
            enemyTree.Nodes.Add("5350 BLANK");
            enemyTree.Nodes.Add("5351 BLANK");
            enemyTree.Nodes.Add("5352 BLANK");
            enemyTree.Nodes.Add("5353 BLANK");
            enemyTree.Nodes.Add("5354 BLANK");
            enemyTree.Nodes.Add("5355 BLANK");
            enemyTree.Nodes.Add("5356 BLANK");
            enemyTree.Nodes.Add("5357 BLANK");
            enemyTree.Nodes.Add("5358 BLANK");
            enemyTree.Nodes.Add("5359 BLANK");
            enemyTree.Nodes.Add("5360 BLANK");
            enemyTree.Nodes.Add("5361 BLANK");
            enemyTree.Nodes.Add("5362 BLANK");
            enemyTree.Nodes.Add("5363 BLANK");
            enemyTree.Nodes.Add("5364 BLANK");
            enemyTree.Nodes.Add("5365 BLANK");
            enemyTree.Nodes.Add("5366 BLANK");
            enemyTree.Nodes.Add("5367 BLANK");
            enemyTree.Nodes.Add("5368 BLANK");
            enemyTree.Nodes.Add("5369 BLANK");
            enemyTree.Nodes.Add("5370 BLANK");
            enemyTree.Nodes.Add("5371 BLANK");
            enemyTree.Nodes.Add("5372 BLANK");
            enemyTree.Nodes.Add("5373 BLANK");
            enemyTree.Nodes.Add("5374 BLANK");
            enemyTree.Nodes.Add("5375 BLANK");
            enemyTree.Nodes.Add("5376 BLANK");
            enemyTree.Nodes.Add("5377 BLANK");
            enemyTree.Nodes.Add("5378 BLANK");
            enemyTree.Nodes.Add("5379 BLANK");
            enemyTree.Nodes.Add("5380 BLANK");
            enemyTree.Nodes.Add("5381 BLANK");
            enemyTree.Nodes.Add("5382 BLANK");
            enemyTree.Nodes.Add("5383 BLANK");
            enemyTree.Nodes.Add("5384 BLANK");
            enemyTree.Nodes.Add("5385 BLANK");
            enemyTree.Nodes.Add("5386 BLANK");
            enemyTree.Nodes.Add("5387 BLANK");
            enemyTree.Nodes.Add("5388 BLANK");
            enemyTree.Nodes.Add("5389 BLANK");
            enemyTree.Nodes.Add("5390 BLANK");
            enemyTree.Nodes.Add("5391 BLANK");
            enemyTree.Nodes.Add("5392 BLANK");
            enemyTree.Nodes.Add("5393 BLANK");
            enemyTree.Nodes.Add("5394 BLANK");
            enemyTree.Nodes.Add("5395 BLANK");
            enemyTree.Nodes.Add("5396 BLANK");
            enemyTree.Nodes.Add("5397 BLANK");
            enemyTree.Nodes.Add("5398 BLANK");
            enemyTree.Nodes.Add("5399 BLANK");
            enemyTree.Nodes.Add("5400 BLANK");
            enemyTree.Nodes.Add("5401 BLANK");
            enemyTree.Nodes.Add("5402 BLANK");
            enemyTree.Nodes.Add("5403 BLANK");
            enemyTree.Nodes.Add("5404 BLANK");
            enemyTree.Nodes.Add("5405 BLANK");
            enemyTree.Nodes.Add("5406 BLANK");
            enemyTree.Nodes.Add("5407 BLANK");
            enemyTree.Nodes.Add("5408 BLANK");
            enemyTree.Nodes.Add("5409 BLANK");
            enemyTree.Nodes.Add("5410 BLANK");
            enemyTree.Nodes.Add("5411 BLANK");
            enemyTree.Nodes.Add("5412 BLANK");
            enemyTree.Nodes.Add("5413 BLANK");
            enemyTree.Nodes.Add("5414 BLANK");
            enemyTree.Nodes.Add("5415 BLANK");
            enemyTree.Nodes.Add("5416 BLANK");
            enemyTree.Nodes.Add("5417 BLANK");
            enemyTree.Nodes.Add("5418 BLANK");
            enemyTree.Nodes.Add("5419 BLANK");
            enemyTree.Nodes.Add("5420 BLANK");
            enemyTree.Nodes.Add("5421 BLANK");
            enemyTree.Nodes.Add("5422 BLANK");
            enemyTree.Nodes.Add("5423 BLANK");
            enemyTree.Nodes.Add("5424 BLANK");
            enemyTree.Nodes.Add("5425 BLANK");
            enemyTree.Nodes.Add("5426 BLANK");
            enemyTree.Nodes.Add("5427 BLANK");
            enemyTree.Nodes.Add("5428 BLANK");
            enemyTree.Nodes.Add("5429 BLANK");
            enemyTree.Nodes.Add("5430 BLANK");
            enemyTree.Nodes.Add("5431 BLANK");
            enemyTree.Nodes.Add("5432 BLANK");
            enemyTree.Nodes.Add("5433 BLANK");
            enemyTree.Nodes.Add("5434 BLANK");
            enemyTree.Nodes.Add("5435 BLANK");
            enemyTree.Nodes.Add("5436 BLANK");
            enemyTree.Nodes.Add("5437 BLANK");
            enemyTree.Nodes.Add("5438 BLANK");
            enemyTree.Nodes.Add("5439 BLANK");
            enemyTree.Nodes.Add("5440 BLANK");
            enemyTree.Nodes.Add("5441 BLANK");
            enemyTree.Nodes.Add("5442 BLANK");
            enemyTree.Nodes.Add("5443 BLANK");
            enemyTree.Nodes.Add("5444 BLANK");
            enemyTree.Nodes.Add("5445 BLANK");
            enemyTree.Nodes.Add("5446 BLANK");
            enemyTree.Nodes.Add("5447 BLANK");
            enemyTree.Nodes.Add("5448 BLANK");
            enemyTree.Nodes.Add("5449 BLANK");
            enemyTree.Nodes.Add("5450 BLANK");
            enemyTree.Nodes.Add("5451 BLANK");
            enemyTree.Nodes.Add("5452 BLANK");
            enemyTree.Nodes.Add("5453 BLANK");
            enemyTree.Nodes.Add("5454 BLANK");
            enemyTree.Nodes.Add("5455 BLANK");
            enemyTree.Nodes.Add("5456 BLANK");
            enemyTree.Nodes.Add("5457 BLANK");
            enemyTree.Nodes.Add("5458 BLANK");
            enemyTree.Nodes.Add("5459 BLANK");
            enemyTree.Nodes.Add("5460 BLANK");
            enemyTree.Nodes.Add("5461 BLANK");
            enemyTree.Nodes.Add("5462 BLANK");
            enemyTree.Nodes.Add("5463 BLANK");
            enemyTree.Nodes.Add("5464 BLANK");
            enemyTree.Nodes.Add("5465 BLANK");
            enemyTree.Nodes.Add("5466 BLANK");
            enemyTree.Nodes.Add("5467 BLANK");
            enemyTree.Nodes.Add("5468 BLANK");
            enemyTree.Nodes.Add("5469 BLANK");
            enemyTree.Nodes.Add("5470 BLANK");
            enemyTree.Nodes.Add("5471 BLANK");

            string[] values = new[] {
            "Unknown Flag",
            "00 No Flag",
            "01 SP Cost",
            "02 IV",
            "03 Speed Mod IV",
            "04 Base Accuracy",
            "05 Accuracy Mod IV",
            "A4 Never Miss IV",
            "2C Splash Damage%",
            "3F Inflict Chance",
            "48 Skill Damage%",
            "4A Amount Restored IV",
            "53 Min Hit #",
            "54 Max Hit #",
            "59 Poison Damage%",
            "D9 Buff Turns",
            "FF IV",
            "1FB Percent Heal",
            "21B Knockdown Chance"
            };
            comboBoxSkillFlag1.Items.AddRange(values);
            comboBoxSkillFlag2.Items.AddRange(values);
            comboBoxSkillFlag3.Items.AddRange(values);
            comboBoxSkillFlag4.Items.AddRange(values);
            comboBoxSkillFlag5.Items.AddRange(values);
            comboBoxSkillFlag6.Items.AddRange(values);
            comboBoxSkillFlag7.Items.AddRange(values);
            comboBoxSkillFlag8.Items.AddRange(values);

            TreeNodeCollection nodeCollect = enemyTree.Nodes;
            enemyTree.SelectedNode = nodeCollect[0];
        }

        private void FormQSkillEditor_Load(object sender, EventArgs e)
        {

        }

        private void enemyTree_AfterSelect(object sender, TreeViewEventArgs e)
        {

            //Value 1 is distance / offset from the start of the file to the start of the array ("Start" in 010) (The first byte is 0) 
            //Value 2 is how many bytes / hexes are in a "row"   (First byte is 1 NOT 0)
            //Value 3 is how many bytes into the row info starts (The first byte is byte 0)

            richTextBoxMaxLv.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 0).ToString("D");
            richTextBoxSkillType.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 2).ToString("D");  
            richTextBoxBindType.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 4).ToString("D");

            richTextBox4.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 6].ToString("D");
            richTextBoxRange.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 7].ToString("D");
            richTextBoxTargetType.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 8].ToString("D");

            richTextBoxTargetTeam.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 9].ToString("D");
            richTextBoxAvailability.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 10].ToString("D");
            richTextBox9.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 11].ToString("D");
            richTextBox10.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 12].ToString("D");

            richTextBox11.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 16).ToString("D");

            richTextBox12.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 19].ToString("D");
            richTextBoxElement.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 20).ToString("D");
            richTextBox14.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 22].ToString("D");
            richTextBox15.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 23].ToString("D");

            richTextBoxInflictCheck.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 24).ToString("D");
            richTextBoxAilments.Text = BitConverter.ToUInt16(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 26).ToString("D");

            

            richTextBox28.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 28].ToString("D");
            richTextBox29.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 29].ToString("D");
            richTextBox30.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 30].ToString("D");
            richTextBox31.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 31].ToString("D");
            richTextBox32.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 32].ToString("D");

            richTextBox33.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 33].ToString("D");
            richTextBox36.Text = enemydata_array[0 + (enemyTree.SelectedNode.Index * 392) + 36].ToString("D");



            //Attempting to add skill flags
            textBoxFlag1Lv1.Text = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 44).ToString("D");
            textBoxFlag2Lv1.Text = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 88).ToString("D");
            textBoxFlag3Lv1.Text = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 132).ToString("D");
            textBoxFlag4Lv1.Text = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 176).ToString("D");
            textBoxFlag5Lv1.Text = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 220).ToString("D");
            textBoxFlag6Lv1.Text = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 264).ToString("D");
            textBoxFlag7Lv1.Text = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 308).ToString("D");
            textBoxFlag8Lv1.Text = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 352).ToString("D");


            string VarSkillFlag = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 40).ToString("D"); //We put the hex into this string, and if the string is read, we make the text appear in the combo box.
            nameOfFlags(0);

            VarSkillFlag = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 84).ToString("D"); //We put the hex into this string, and if the string is read, we make the text appear in the combo box.
            nameOfFlags(1);

            VarSkillFlag = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 128).ToString("D"); //We put the hex into this string, and if the string is read, we make the text appear in the combo box.
            nameOfFlags(2);

            VarSkillFlag = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 172).ToString("D"); //We put the hex into this string, and if the string is read, we make the text appear in the combo box.
            nameOfFlags(3);

            VarSkillFlag = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 216).ToString("D"); //We put the hex into this string, and if the string is read, we make the text appear in the combo box.
            nameOfFlags(4);

            VarSkillFlag = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 260).ToString("D"); //We put the hex into this string, and if the string is read, we make the text appear in the combo box.
            nameOfFlags(5);

            VarSkillFlag = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 304).ToString("D"); //We put the hex into this string, and if the string is read, we make the text appear in the combo box.
            nameOfFlags(6);

            VarSkillFlag = BitConverter.ToUInt32(enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 348).ToString("D"); //We put the hex into this string, and if the string is read, we make the text appear in the combo box.
            nameOfFlags(7);


            void nameOfFlags(int box_id)
            {
                //skillTree.Nodes.Add("Function Is Working!" + VarcomboBoxSkillFlag);
                boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("Unknown Flag");
                if (VarSkillFlag == "0") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("00 No Flag"); }
                if (VarSkillFlag == "1") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("01 SP Cost"); }
                if (VarSkillFlag == "3") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("03 Speed Mod IV"); }
                if (VarSkillFlag == "4") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("04 Base Accuracy"); }
                if (VarSkillFlag == "5") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("05 Accuracy Mod IV"); }
                if (VarSkillFlag == "44") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("2C Splash Damage%"); }
                if (VarSkillFlag == "63") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("3F Inflict Chance"); }
                if (VarSkillFlag == "72") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("48 Skill Damage%"); }
                if (VarSkillFlag == "74") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("4A Amount Restored IV"); }
                if (VarSkillFlag == "83") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("53 Min Hit #"); }
                if (VarSkillFlag == "84") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("54 Max Hit #"); }
                if (VarSkillFlag == "89") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("59 Poison Damage%"); }
                if (VarSkillFlag == "164") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("A4 Never Miss IV"); }
                if (VarSkillFlag == "217") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("D9 Buff Turns"); }
                if (VarSkillFlag == "507") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("1FB Percent Heal"); }
                if (VarSkillFlag == "539") { boxes[box_id].SelectedIndex = boxes[box_id].FindStringExact("21B Knockdown Chance"); }




            }

        }

        private void buttonSave_Click(object sender, EventArgs e) //Save Button
        {
            //B! .TryParse(Name! .Text, out type! value! ); { Form1.ByteWriter( value! , enemydata_array, StartingHex! + (treeView1.SelectedNode.Index * RowSize! ) + ArrayOfset! ); }
            //B=Byte size, 1="Byte" 2="UInt16" 4="UInt32"         Name!=the name of the textbox        type!= byte / ushort / uint, only include this in the FIRST time this ever happens in a form, later copies ommit this!
            //value!=Name of variable that holds the byte type (so byte/short/int has diffrent names)       StartingHex!= The hex offset      RowSize!=How many bytes in a row    Arrayofset! = how far into the row do we start grabbing info or saving it
            
            UInt16.TryParse(richTextBoxMaxLv.Text, out ushort value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 0); } //First 2 byte save
            UInt16.TryParse(richTextBoxSkillType.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 2); } 
            UInt16.TryParse(richTextBoxBindType.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 4); } 
            
            Byte.TryParse(richTextBox4.Text, out byte value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 6); } //First 1 byte save
            Byte.TryParse(richTextBoxRange.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 7); }
            Byte.TryParse(richTextBoxTargetType.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 8); }
            Byte.TryParse(richTextBoxTargetTeam.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 9); }
            Byte.TryParse(richTextBoxAvailability.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 10); }
            Byte.TryParse(richTextBox9.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 11); }
            Byte.TryParse(richTextBox10.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 12); }

            UInt16.TryParse(richTextBox11.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 16); }
            
            Byte.TryParse(richTextBox12.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 19); }
            UInt16.TryParse(richTextBoxElement.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 20); }
            Byte.TryParse(richTextBox14.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 22); }
            Byte.TryParse(richTextBox15.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 23); }

            UInt16.TryParse(richTextBoxInflictCheck.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 24); }
            UInt16.TryParse(richTextBoxAilments.Text, out value16); { Form1.ByteWriter(value16, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 26); }

            Byte.TryParse(richTextBox28.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 28); }
            Byte.TryParse(richTextBox29.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 29); }
            Byte.TryParse(richTextBox30.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 30); }
            Byte.TryParse(richTextBox31.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 31); }
            Byte.TryParse(richTextBox32.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 32); }

            Byte.TryParse(richTextBox33.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 33); }
            Byte.TryParse(richTextBox36.Text, out value8); { Form1.ByteWriter(value8, enemydata_array, 0 + (enemyTree.SelectedNode.Index * 392) + 36); }
            
            

            File.WriteAllBytes(Properties.Settings.Default.PQRomFS + "\\battle\\table\\skilltable.tbl", enemydata_array); //saves to the path i set, everything in the array/
        }
    }
}
